### ISSUE TITLE
Europe/Paris timezone bug

### ISSUE THREAD

**Issue by Niromash** [fullstack-build/tslog#105]
Hello, there is a slight problem with the display of the time for the Europe/Paris timezone, instead of 00h00 it changes to 24h00
![Sans titre](https://user-images.githubusercontent.com/27890221/120086033-5d446180-c0dd-11eb-97ae-2317bcfa9173.png)

**Comment by terehov** [comment]
Can you verify if this version fixes your issue? Thank you. 

https://github.com/fullstack-build/tslog/releases/tag/v3.2.2
