### ISSUE TITLE
Bug: JSON type returning hostname and instance name when supposed to be hidden by default

### ISSUE THREAD

**Issue by blakejoy** [fullstack-build/tslog#110]
**Describe the bug**
The json type is returning the full logObject regardless of the values provided to be hidden/displayed in the settings.

**To Reproduce**
1. Create new Logger with settings param {type: 'json'}
2. Pass a string to Logger instance to see the output.

**Expected behavior**
The log output when formatted as json should not display the values that are supposed to be hidden by default. Ie. hostname, instancename.

**Node.js Version**
14.16.0

**OS incl. Version**
macOS 10.15.7

**Comment by hydeenoble** [comment]
@blakejoy Please did you get a way around this?

**Comment by blakejoy** [comment]
I ended up not using this @hydeenoble 🥲

**Comment by terehov** [comment]
There is a new, completely rewritten version (4.0) which handles it completely different and should solve this out of the box. In addition, you can also overwrite every step of the log process. Give it a go and let me know if that solves your problem: 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

Thanks.

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)
