### ISSUE TITLE
tslog shouldn't modify global util.inspect styles by default

### ISSUE THREAD

**Issue by ejose19** [fullstack-build/tslog#112]
**Describe the bug**
Currently, `tslog` overwrites `util.inspect` styles by its own:
https://github.com/fullstack-build/tslog/blob/2760b4144691a354126059a9d100a8c3c4879895/src/LoggerWithoutCallSite.ts#L75-L87
https://github.com/fullstack-build/tslog/blob/2760b4144691a354126059a9d100a8c3c4879895/src/LoggerHelper.ts#L136-L144

which will affect other consumers of `util.inspect`, this shouldn't be enabled by default and instead by provided as an export (ie: `CustomHighlightStyles` that must be explicitly be used as:

```typescript
import { Logger, CustomHighlightStyles } from "tslog";

const log = new Logger({ prettyInspectHighlightStyles: CustomHighlightStyles });
```

**To Reproduce**
1. Create a logger with default options
2. Use `console.log(inspect({ foo: "bar" }, { colors: true }))`
3. Notice how the colors changed implicitly

**Expected behavior**
Global shouldn't be modified implicitly

**Screenshots**
N/A

**Additional context**
I'm aware `util.inspect` doesn't provide a way to create a custom inspect function (ie: `new Inspect()`), so in case this library needs to modify global inspect at least it should be explicitly (and with a docs warning).

**Node.js Version**
16.3.0

**OS incl. Version**
Archlinux

**Comment by terehov** [comment]
I agree. I am going to put in some thoughts.
