### ISSUE TITLE
Feature Request: Simpler transport

### ISSUE THREAD

**Issue by JustinGrote** [fullstack-build/tslog#113]
**Description / Use Case for a Feature**

Because the severity of a log is included with the logObject, there should be a simpler transport implementation option similar to the `IStd` interface for prettyprint.
```typescript
export interface TSimpleTransport {
  log: (logObject: ILogObject) => void
}
```

And this type added as an overload to `attachTransport`

This would allow a transport logger to take out all the per-severity boilerplate and still support minLevel (because the logger simply wouldn't call the transport unless minlevel is reached). It would also remain backwards compatible if new severity types are added to the interface (which would otherwise be breaking for transports with the current implementation)

Simple implementation:

```typescript
class ConsoleLogTransport implements TSimpleTransport {
  //Special processing for severity differences can go here
  log: (logObject: ILogObject) => {
    console.log(logObject.argumentsArray.ToString())
  }
}
```

An example existing transport implementation that could have about 10 lines cut out of it if this is implemented:
```typescript
class DebugConsoleOutput implements IStd {
    write(message: string) {console.log(message)}
}

/**
 * Writes TSLog Pretty Print messages to the vscode debug console. It requires the logger during construction to import
 * its pretty print preferences
 *
 * @class DebugConsoleTransport
 * @implements {TTransportLogger<(ILogObject) => void>}
 */
class DebugConsoleTransport implements TTransportLogger<(logObject: ILogObject) => void> {
    private readonly debugConsoleOutput = new DebugConsoleOutput()
    constructor(
        private readonly logger: Logger
    ){}
    log(logObject: ILogObject): void {
        this.logger.printPrettyLog(this.debugConsoleOutput, logObject)
    }
    silly = this.log
    debug = this.log
    trace = this.log
    info = this.log
    warn = this.log
    error = this.log
    fatal = this.log
}
```

**Comment by terehov** [comment]
V4 beta is out, and you can now overwrite any aspect of the process, even the transport. It now works both ways, either as an attached transport or as on overwrite.
Give it a go and let me know if that solves your problem. I'll publish the final version as soon as I have gathered enough feedback. 

- Attached transport: 
https://github.com/fullstack-build/tslog/blob/v4/tests/Nodejs/11_Transports.test.ts

- Overwrite the default transport: 
- Pretty: 
https://github.com/fullstack-build/tslog/blob/v4/tests/Nodejs/10_Overwrites.test.ts#L83

- JSON: 
https://github.com/fullstack-build/tslog/blob/v4/tests/Nodejs/10_Overwrites.test.ts#L114


- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)
