### ISSUE TITLE
Feature Request: PrintPrettyLog should have option to send entire string as one write call to IStd

### ISSUE THREAD

**Issue by JustinGrote** [fullstack-build/tslog#114]
**Description / Use Case for a Feature**

Currently when implementing a custom output via IStd, write gets called 5 times for a simple message, which makes processing more complicated than it needs to be (buffering the output and then looking maybe for a \n to decide when a log entry is complete, and if I want a multiline output from prettyprint, gets even more complicated especially if the log message has newlines in it)

Instead, a not-breaking simplification would be to add a boolean option to PrintPrettyLog called `singleWrite` or something that will only call the IStd write method once with the entire prettyprint result string, newlines and all.

## Workaround
Use a custom delimiter as a sort of flag to indicate there is more to come. This is a bad code smell.
```typescript
/** ASCII Section Break character */
const delimiter = String.fromCharCode(31)

class DebugConsoleOutput implements IStd {
    private readonly buffer = new Array<string>()
    write(message: string) {
        if (message.endsWith(delimiter)) {
            this.buffer.push(
                message.replace(delimiter, "\t")
            )
            return
        } else {
            this.buffer.push(message)
            console.log(this.buffer.join(''))
        }
    }
}
```

**Comment by terehov** [comment]
Thank you for this valid input. There is a new, completely rewritten version (4.0) which solves this problem and also makes it completely configurable. This particular case should work out of the box. 
Give it a go and let me know if that solves your problem: 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)
