### ISSUE TITLE
Bug: Delimiter is inconsistent in prettyprint

### ISSUE THREAD

**Issue by JustinGrote** [fullstack-build/tslog#115]
**Describe the bug**
When trying to prettyprint to a custom istd, the delimiter is sometimes in the wrong place, e.g. before an ANSI color reset
![image](https://user-images.githubusercontent.com/15258962/127326370-8bceea45-b323-4c0f-b989-2e0b2701332f.png)
Or just missing completely
![{113145A4-D284-4238-9430-9D5531AC7A2C}](https://user-images.githubusercontent.com/15258962/127326547-79abde07-edc3-4e2b-96da-23f8d3b509ee.png)

**Comment by terehov** [comment]
There is a new `next` release of version 4.0. Now you can use templates and change the output completely, incl. delimiters.
Could you give it a go and see if it helps? I would appreciate your feedback. 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`


Here is an example of how to use it: 
https://github.com/fullstack-build/tslog/blob/v4/tests/Nodejs/7_pretty_Settings.test.ts#L127

This is how the default log template looks like: 
https://github.com/fullstack-build/tslog/blob/v4/src/BaseLogger.ts#L22

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)
