### ISSUE TITLE
Feature Request: [use formatWithOptions instead of format inside _formatAndHideSensitive]

### ISSUE THREAD

**Issue by adavidhon** [fullstack-build/tslog#123]
Usage of util.format inside _formatAndHideSensitive breaks the ingestion of json logs by filebeat due to the errorString containing newlines. Filebeat can only read json objects if it is printed on a single line. Moving to formatWithOptions will allow us to use the breakLength property of InspecOptions to decide how long the string is until we break it with a newline (so we can set it to Infinity if we want). 

We can also make the errorString optional?

**Comment by terehov** [comment]
I’ll have a look but that should be doable.

**Comment by adavidhon** [comment]
Hi @terehov, did you only change it for pretty formatting? We kind of need that for json formatting due to issues that filebeat has with ingesting json logs with newlines in it

**Comment by terehov** [comment]
Would be awesome if you could put it down into a MR 👍

**Comment by terehov** [comment]
@adavidhon Have a look here, does it fix it for you? 
https://github.com/fullstack-build/tslog/commit/b8c22d187de63a14fb2b46e00eb259c625a96ef8

**Comment by adavidhon** [comment]
I'll take a look at it shortly
