### ISSUE TITLE
Bug: errors out when using react native with metro server

### ISSUE THREAD

**Issue by mat2718** [fullstack-build/tslog#124]
**Describe the bug**
errors out anytime it being run in react native app/ also had to manually install os and path. 

**To Reproduce**

1. install tslog
2. import Logger to a file like in the example given
3. run React-native run android
4. See error:
5.  WARN  Require cycle: node_modules\os\index.js -> node_modules\os\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. ERROR  TypeError: _$$_REQUIRE(_dependencyMap[1], "os").hostname is not a function. (In '_$$_REQUIRE(_dependencyMap[1], "os").hostname()', '_$$_REQUIRE(_dependencyMap[1], "os").hostname' is undefined)
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Expected behavior**

**Screenshots**

**Additional context**
running it within a react native app using a metro server 

**Node.js Version**
16.x.x

**OS incl. Version**
Windows 11

**Comment by terehov** [comment]
There is a new `next` release of version 4.0. It interacts less with the native V8 and should help with this issue. Could you give it a go and see if it helps? I would appreciate your feedback. 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)
