### ISSUE TITLE
Feature Request: [Log in separate thread]

### ISSUE THREAD

**Issue by orlandodiaz** [fullstack-build/tslog#128]
**Description / Use Case for a Feature**

It seems this library is adding quite some additional overhead for me, probably because I'm also logging to files. The overhead is noticeable and a problem for low latency applications. This problem would be solved if the logging was done in a separate thread. Does this library support this?

**Comment by terehov** [comment]
That sounds quite a lot indeed. 
Can you give me some more details on your use case? How do you use it? 

Btw. version 4.0 is going to be was leaner and pluggable.

**Comment by terehov** [comment]
There is a new `next` release of version 4. As mentioned before, it is way leaner, more flexible and interacts less with the native V8. You can still put it into a worker thread, if needed. Could you give it a go and see if it helps? I would appreciate your feedback. 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`
