### ISSUE TITLE
Bug: TRequestIdFunction is too stricly typed

### ISSUE THREAD

**Issue by jraoult** [fullstack-build/tslog#137]
**Describe the bug**
While implementing a request id provider function, I realised that [it is supported to return `undefined`](https://github.com/fullstack-build/tslog/blob/91784f2fa6fe1a5c5fe233c1807017992ea75b12/src/LoggerWithoutCallSite.ts#L395) from a [`TRequestIdFunction`](https://github.com/fullstack-build/tslog/blob/91784f2fa6fe1a5c5fe233c1807017992ea75b12/src/interfaces.ts#L42) despite what the typing is enforcing. The `requestId` will not be shown in the log trace, which is very handy.

I think the type should be updated to reflect the runtime behaviour:

```ts
export type TRequestIdFunction = () => string | undefined;
```

**Comment by terehov** [comment]
That's correct, thank you. I'll fix it in the next release :-)

**Comment by terehov** [comment]
https://github.com/fullstack-build/tslog/releases/tag/v3.3.4
