### ISSUE TITLE
Bug: [BUG] Child instance cannot import settings from parent

### ISSUE THREAD

**Issue by dever23b** [fullstack-build/tslog#146]
**Describe the bug**
The `LoggerWithoutCallSite.settings` getter method merges `this._parentOrDefaultSettings` and `this._mySettings` in a manner which results .  As of this writing, the code uses spread operators to merge the two property sets; however, this method of merging simply overwrites and does not prevent a "falsy" value from overwriting a "truthy" value.  Accordingly, settings that are left undefined in a child will still overwrite the corresponding setting from the parent.  The merging process must consider whether a child setting is defined prior to overwriting the defaults, or the defaults will never be used.

**To Reproduce**
```typescript
import { Logger } from 'tslog';
const parent = new Logger({ name: 'parent' }); // parent.settings.name = 'parent'
const child = parent.getChildLogger({ requestId: 'foo' }); // parent.settings.name = undefined

child.info('test'); 
// when eventually passed through prettyPrintLog, 
// parent.settings.name is evaluated to undefined and not printed
```

**Expected behavior**
Child logger settings should be merged with parent, as the documentation suggests, such that only _defined_ settings overwrite parent/defaults.

**Additional context**
https://github.com/fullstack-build/tslog/blob/bbc8bab8b5e37127716c1271df2a65ca81448532/src/LoggerWithoutCallSite.ts#L133-L141

**Node.js Version**
v16.16.0

**Comment by terehov** [comment]
@dever23b Thank you for reporting this bug. 

However, the faulty code isn't the spread operator, it's rather here: 
https://github.com/fullstack-build/tslog/blob/bbc8bab8b5e37127716c1271df2a65ca81448532/src/LoggerWithoutCallSite.ts#L170

It's the way the name gets replaced in certain scenarios. I have fixed it and going to publish a new version with some more bugfixes shortly.

**Comment by terehov** [comment]
https://github.com/fullstack-build/tslog/releases/tag/v3.3.4

**Comment by dever23b** [comment]
Thanks!  I'll get updated and test this week.

**Comment by dever23b** [comment]
I pulled the latest version and tested this.  It works!  Thanks again.
