### ISSUE TITLE
Feature Request: [add doc for webpack 5]

### ISSUE THREAD

**Issue by xinatcg** [fullstack-build/tslog#147]
**Description / Use Case for a Feature**

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

get error when use webpack 5

**Comment by terehov** [comment]
Hello @xinatcg, 

as mentioned in the docs, the current version of `tslog` is a Node.js only library. 
The upcoming version (s. v4 branch) is going to be isomorphic. 

Duplicate to this: 
https://github.com/fullstack-build/tslog/issues/88

**Comment by cgxxv** [comment]
@terehov Did `tslog@4.7.1` support webpack 5 currently?
