### ISSUE TITLE
Feature Request: [custom formatter]

### ISSUE THREAD

**Issue by tomer-refundit** [fullstack-build/tslog#15]
**Description / Use Case for a Feature**
when writing web server its nice thing to see all the logs that relate to one request
this can be done using cls-hooked 
see https://itnext.io/nodejs-logging-made-right-117a19e8b4ce

so custom formatter, or maybe option to make the logger name dynamic(accepting function instead of string)

**Comment by terehov** [comment]
Thanks for your input! 
I'll give it some thoughts and try to come up with a good solution :-)

**Comment by terehov** [comment]
Hey @tomer-refundit, thanks again for your input. That was an interesting read indeed. 
I started working on a `tarceId`. For now, it's just an additional parameter that you can add to a child logger (also working on that as well. You may want to check the discussion here #16) that can either be a `string` or a `Function`. Let me know if this goes in the right direction. Thanks.

**Comment by terehov** [comment]
You can check it out here: 
https://www.npmjs.com/package/tslog/v/2.3.0-1

`npm i tslog@next`

**Comment by terehov** [comment]
It is available in version 2.5.0
https://github.com/fullstack-build/tslog/releases/tag/v2.5.0

Docs: 
https://github.com/fullstack-build/tslog#requestid
