### ISSUE TITLE
Bug: TRACE always exposes the stack trace even if disabled

### ISSUE THREAD

**Issue by lukaszlenart** [fullstack-build/tslog#150]
**Describe the bug**
TRACE always exposes the stack trace even if disabled
https://github.com/fullstack-build/tslog/blob/master/src/LoggerWithoutCallSite.ts#L257

**To Reproduce**
Create a logger and call `logger.trace('boom!')`

**Expected behavior**
The behaviour should be controlled by `settings.exposeStack`

**Node.js Version**
v18.9.0

**OS incl. Version**
macOS 12.6

**Comment by terehov** [comment]
Hello @lukaszlenart, it's actually not a bug, but a documented behaviour:
https://tslog.js.org/#/?id=log-level

>Hint: Log level trace behaves a bit differently compared to all the other log levels. While it is possible to activate a stack trace for every log level, it is already activated for trace by default. That means every trace log will also automatically capture and print its entire stack trace.

However, the upcoming V4 will work as you expect. It is feature complete, and I am working on the documentation:

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`
