### ISSUE TITLE
Feature Request: Add an `audit` method which can use a separate transport

### ISSUE THREAD

**Issue by jamlen** [fullstack-build/tslog#151]
**Description**

I would like to be able to have an `audit` method which can be sent to a specific transport. My use case is that whilst it makes sense for application logging to increase in severity, I'd like to use the same mechanism of logging to log audit messages. In my case I might have a transport which fires them onto a queue which is then consumed... I may just output them onto the console.

Something like this...

```typescript
log.attachTransport(auditEventPublisherTransport)

async function SomeImportantLogic(something: MyThings) {
  log.debug('called with args', { something })
  validateSomething(something)
  const result = await performBusinessLogic(something)
  log.audit('ImportantLogic completed', { user: userContext.identity, requestContext: request.contextId })
}
```
I've seen some of the `v4` stuff and I think it might be achievable with that, but not sure.

**Comment by terehov** [comment]
I think so too. Can you give it a go and let me know if something is still missing? 

Here are the docs: [tslog.js.org](https://tslog.js.org)

**Comment by terehov** [comment]
Closing issue due to missing feedback.
