### ISSUE TITLE
tsdoc is down

### ISSUE THREAD

**Issue by danmichaelo** [fullstack-build/tslog#154]
https://tslog.js.org/tsdoc/ is not working :(

![image](https://user-images.githubusercontent.com/434495/198204280-7e1067f0-78b7-4e8b-8625-9a876a47cb03.png)

**Comment by terehov** [comment]
tsdoc is back on again. 
The reason is that I was about to release V4, but didn't manage to get tsdoc (typedoc) to work with `tslog` being an ESM only module.
