### ISSUE TITLE
Bug: [BUG]

### ISSUE THREAD

**Issue by caboyer** [fullstack-build/tslog#156]
**Describe the bug**
I feel weird not to understand why I can''t get Tslog to print correctly :
- the name of the class it is in, when the log is called from a constructor. Your doc definitely shows it can (MyClass.constructor) but I end up with undefined.constructor.
- the name of the function it is runned in, in case that function calls a forEach, map or promise, and logs is inside of the code. 

**To Reproduce**

I'll print some piece of code :
1st issue - 
```js
export default class <CLASSNAME> extends AbstractClassifier {
 constructor() {
    super();
    if (!assistant) {
      logger.info(`Using Assistant located @ ${...}`);
      assistant = ...
    }
    this.assistant = assistant;
  }
```

This will output 
```bash
2022-11-08 13:08:30.340  INFO  [<FILENAME> undefined.constructor] Using Assistant located @ ...
```

2nd issue - 
```js
// it is in the same class as extract 1 - above
async fetchModels(locales) {
    try {
      ...
      locales.forEach((oneLocale) => {
        logger.info(`Retrieving access to ${oneLocale} model `)
        ...
     })
```
will output
```bash
2022-11-08 13:08:31.109  INFO  [<FILENAME>  undefined.<anonymous>] Retrieving access to fr-FR model
2022-11-08 13:08:31.111  INFO  [<FILENAME>  undefined.<anonymous>] Retrieving access to en-US model
2022-11-08 13:08:31.112  INFO  [<FILENAME>  undefined.<anonymous>] Retrieving access to nl-NL model
```

**Expected behavior**
I believe it is not a bug, but my way to write maybe ? 
But I have no clue what I did wrong.

I expect my logs to look like the example on the website
![image](https://user-images.githubusercontent.com/73245391/200774768-4b17e382-cfca-40b2-8ff9-8d0075838632.png)
so instead of undefined have my `<CLASSNAME>.constructor` & `<CLASSNAME>.fetchModels` I guess ?

**Node.js Version**
e.g. 16.13.1

**OS incl. Version**
e.g. windiws 10 Entreprise 20H2

**Comment by terehov** [comment]
Thank you for reporting. 
Unfortunately, I decided to remove this feature in version >= 4 to improve performance and also make it work in browsers without interfering with the Node.js V8 API. Is there a particular reason you would need this information?

**Comment by caboyer** [comment]
It makes debugging easier as we have a relative trace without having to print the whole thing.

Thank you for your quick response. I'll just disable the option !
