### ISSUE TITLE
Bug: [BUG] "name" is missing

### ISSUE THREAD

**Issue by lukaszlenart** [fullstack-build/tslog#159]
**Describe the bug**

I tried to upgraded to the latest tslog 4.0.1 but the "name" parameter is missing - is see it in the docs, but when using TypeScript it isn't available

**Node.js Version**
v18.12.1

**OS incl. Version**
macOS 13.0.1

**Comment by terehov** [comment]
`tslog` follows a semantic release policy. A major version change (from v3.x to v4.x) indicates breaking changes. Therefore, this not a bug, but a change. 

`tslog` >=4 is way more flexible, however, less limiting when it comes to configuration. There are so many different use cases (especially when it comes to integration with 3rd party services) that I decided to open up the API. 

However, most use cases can still be achieved elegantly. 
For example, the `name`: 
Before, only a number of parameters were allowed (e.g. the `name`). Now you can decide yourself, how the log object should look like. That's the second parameter of the constructor (https://tslog.js.org/#/?id=defining-and-accessing-logobj)

So a name would look like this: 
```typescript

const log = new Logger({ type: "json" }, { name: "DefaultLogger" });

log.silly("foo bar");
```

**Comment by lukaszlenart** [comment]
I was misled by the docs, now I see they were upgraded, thanks!
