### ISSUE TITLE
Bug: [BUG]

### ISSUE THREAD

**Issue by kevintechie** [fullstack-build/tslog#166]
**Describe the bug**
Using the placeholder ```{{dateIsoStr}}``` returns "{{dateIsoStr}}" in the rendered log output

**To Reproduce**

```
test("stylePrettyLogs: false / prettyLogTemplate - shortcut: {{dateIsoStr}}", (): void => {
  const logger = new Logger({
    type: "pretty",
    prettyLogTemplate: "**{{dateIsoStr}}**",
    stylePrettyLogs: false,
  });
  logger.log(1234, "testLevel", "Test");
  expect(getConsoleLog()).toContain(`**${new Date().toISOString().replace("T", " ").replace("Z", "").split(".")[0]}`);
  expect(getConsoleLog()).toContain("** Test");
});
```

**Expected behavior**
Shortcut should render as if template string was ```{{yyyy}}.{{mm}}.{{dd}} {{hh}}:{{MM}}:{{ss}}:{{ms}}```

**Node.js Version**
16

**OS incl. Version**
Ubuntu 20.04

**Comment by terehov** [comment]
Fixed in V4.2.0
