### ISSUE TITLE
Bug: [BUG]

### ISSUE THREAD

**Issue by kevintechie** [fullstack-build/tslog#168]
**Describe the bug**
Using ```{{name}}``` placeholder renders extra leading space in log output.

**To Reproduce**

```
test("name placeholder should not have leading space", (): void => {
  const logger = new Logger({
    type: "pretty",
    name: "something",
    prettyLogTemplate: "**{{name}}**",
    stylePrettyLogs: false,
  });
  logger.log(1234, "testLevel", "Test");
  expect(getConsoleLog()).toContain("**something**");
  expect(getConsoleLog()).toContain("** Test");
});
```

**Expected behavior**
```{{name}}``` placeholder should render without leading space (e.g.: "\*\*something\*\*")

**Node.js Version**
16

**OS incl. Version**
Ubuntu 20.04

**Comment by terehov** [comment]
Fixed in V4.2.0
