### ISSUE TITLE
Feature Request: Add prettyTemplateString placeholder to render date and time in ISO format

### ISSUE THREAD

**Issue by kevintechie** [fullstack-build/tslog#170]
**Description / Use Case for a Feature**
Currently, in order to render a standard ISO format date time string to the log, you have to manually create a template string with the individual date and time placeholders and literal string components. There should be a way to do this with a single placeholder. For example: `{{rawIsoStr}}`.

**Comment by terehov** [comment]
Fixed here: 
https://github.com/fullstack-build/tslog/pull/171

And in V4.2.0
