### ISSUE TITLE
Feature Request: ESM only?

### ISSUE THREAD

**Issue by terehov** [fullstack-build/tslog#173]
What do you guys think? 
Is ESM enough nowadays, or should I add a CJS version too?

**Comment by kevintechie** [comment]
I personally am fine with ESM only as everything we do is with ESM modules. However, dealing with EMS only packages can be frustrating for new programmers when trying to use them with legacy CJS code examples. Also, getting them to work with Jest and transpilers like Babble and Typescript can be completely daunting.

Aside from having to maintain a more complex build process, is there any additional overhead for you to maintain both?

**Comment by dumbasPL** [comment]
Would love to see CJS version

**Comment by prescience-data** [comment]
We run `tslog` in a monorepo which has uncompiled internal TypeScript packages (to avoid a build step for every minor internal change).

Without migrating our entire multi-package application to ESM only, this breaks our execution when calling `jiti` or `esbuild register`.

This is by far the most elegant / "just works" solution I've found for dual target builds fwiw:

https://antfu.me/posts/publish-esm-and-cjs

**Comment by terehov** [comment]
`V4.3.0` supports CJS now too.
