### ISSUE TITLE
Bug: Path to type definitions in package.json is incorrect

### ISSUE THREAD

**Issue by kevintechie** [fullstack-build/tslog#178]
**Describe the bug**
The path to the type definitions is not correct in the package.json file. Currently it points to `./dist/nodejs/types/index.d.ts` but should point to `./dist/types/index.d.ts`

**To Reproduce**

1. Start new project
2. Install tslog
3. Create basic getting started index.ts
4. Notice typescript error in import
5. Compile with tsc and see error

**Expected behavior**
Typescript should be able to find type definitions

**Node.js Version**
18

**OS incl. Version**
Ubuntu 20.04

**Comment by terehov** [comment]
That one slipped through... *facepalm*
Fix is coming.
