### ISSUE TITLE
Bug: Can't get tslog to work as ESM module

### ISSUE THREAD

**Issue by kevintechie** [fullstack-build/tslog#179]
**Describe the bug**
tslog not working as an esm package

**To Reproduce**
1. Setup basic project:

package.json
```json
{
  "name": "tslogtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tslog": "^4.3.1"
  },
  "type": "module"
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2022",
    "lib": [
      "ES2022"
    ],
    "module": "ES2022",
    "moduleResolution": "Node",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

index.ts
```typescript
import { Logger } from 'tslog';
const log = new Logger();
log.info('asdf');
```

2. npm i
3. compile w/ tsc
4. node .
5. see error: 
```
import { Logger } from 'tslog'; 

SyntaxError: Named export 'Logger' not found. The requested module 'tslog' is a CommonJS module, which may not support all module.exports as named exports.
```

**Expected behavior**
Should load tslog as esmodule

**Additional context**
Changing module resolution to Node16 causes tsc compile error:

```
index.ts:1:24 - error TS7016: Could not find a declaration file for module 'tslog'. '/home/me/source/tslogTest/node_modules/tslog/dist/nodejs/esm/index.js' implicitly has an 'any' type.
```

**Node.js Version**
18

**OS incl. Version**
Ubuntu 20.04

**Comment by admitad-dev** [comment]
we have this problem too

**Comment by ekho** [comment]
we have this problem to

**Comment by terehov** [comment]
Thank you for reporting. 
Can you please try `V4.4.0` and let me know if it works? Thx. 

```
npm i tslog@4.4.0
```

**Comment by beanaroo** [comment]
@terehov `4.4.0` no longer presents the above error and is working nicely for me. 🎉 (Bundling to ESM using esbuild)

I've also tried it with the above sample with both Node and Node16 module resolutions.

**Comment by ekho** [comment]
@terehov works fine. Thank you!

**Comment by terehov** [comment]
Thank you for your feedback. Happy it works. I’m going to close this issue now.
