### ISSUE TITLE
Bug: Value masking modifies the original object provided to args

### ISSUE THREAD

**Issue by prescience-data** [fullstack-build/tslog#180]
**Describe the bug**
During the value masking process, objects passed to the logger are run through this function:
https://github.com/fullstack-build/tslog/blob/91c03781c9c14b09083347a0c02fe9d799b80ce0/src/BaseLogger.ts#L208

As you can see, it directly modifies the source object, meaning the original value is replaced with the placeholder.

After an object containing masked keys is passed to the logger the original secret is destroyed, which throws errors when using the secret elsewhere in code.

**To Reproduce**

1. Add `maskValuesOfKeys: ["foo"]` rule to options.
```typescript
{
  // ...
  maskValuesOfKeys: ["foo"]
}
```

2. Instantiate a logger.
3. Run 
```typescript
const test = { foo: "bar" } 
logger.info(test)

if(test.foo !== "bar") {
 throw Error(`Test value was modified by logger.`)
}
```

**Expected behavior**
A deep clone of any objects should be performed prior to masking.

**Node.js Version**
e.g. 18.x

**Comment by terehov** [comment]
Thank you for pointing this out. That's definitely a bug and should not be the case. I will fix it and add a test for that.

**Comment by terehov** [comment]
Can you please try `V4.4.0` and let me know if it works? Thx. 

```
npm i tslog@4.4.0
```
