### ISSUE TITLE
Feature Request: Allow to extends the logObj when creating a sub logger

### ISSUE THREAD

**Issue by jraoult** [fullstack-build/tslog#181]
With the new API introduced in v4, I lost the ability to define a `requestId` meta in a sub-logger.

I read the section explaining how to re-implement the `requestId` with the v4 API, but in my app, I have a root logger create like so:
```ts
const rootLogger = new Logger({ type: isProduction ? "json" : "pretty" })
```

and then lower in the "tree" I have the HTTP server that is creating sub logger, and I would want to be able to do:
```ts
const webLogger = rootLogger.getSubLogger(
    {
      name: "web-server",
    },
    { requestId: () => requestIdStorage.getStore()?.requestId }
  );
```

Does it make sense or am I missing something?

**Comment by terehov** [comment]
Thank you, I see your point. 

I will add a second parameter to `getSubLogger` that will allow overwriting that. 

`public getSubLogger(settings?: ISettingsParam<LogObj>, logObj?: LogObj)`

**Comment by jraoult** [comment]
@terehov that would be perfect!

**Comment by terehov** [comment]
I added this in `V4.4.0`. Does it work for you? 

https://github.com/fullstack-build/tslog#sub-logger-with-logobj

**Comment by eugene1g** [comment]
@terehov This allows to _override_ the `logObj`, but is there a way to _extend_ `logObj`? The use-case I have loggers that build on top of each other like so -
`baseLogger` with `hostname` etc -> `httpLogger` adds `IP, userAgent` -> `module1Logger` adds `moduleVersion`-> `service1Logger` adds `userId` etc. When I use the logger at the bottom of this chain, I still need to keep all data parent loggers stuffed into `lobObj`.

**Comment by marcoreni** [comment]
@terehov by looking at the code this should be a simple change:

https://github.com/fullstack-build/tslog/blob/master/src/BaseLogger.ts#L178
```diff
- ) => this)(subLoggerSettings, logObj ?? this.logObj, this.stackDepthLevel);
+ ) => this)(subLoggerSettings, { ...logObj, ...this.logObj }, this.stackDepthLevel);
```

Would you be willing to accept a PR for this?

**Comment by terehov** [comment]
Yes, of course. But we would also need a test and documentation for this 👍🏻

**Comment by rypete** [comment]
Did this ever get anywhere? For me, this is the one thing stopping me from using tslog. I need to be able to maintain parent loggers context information when creating subloggers.
