### ISSUE TITLE
Bug: Sub loggers don't format error properly

### ISSUE THREAD

**Issue by jraoult** [fullstack-build/tslog#183]
**Describe the bug**
While a root logger offers the nice error formatting tslog is loved for, sub loggers just show a list of empty lines prefixed by "error stack:"

**To Reproduce**
Please see the Stackblitz here https://stackblitz.com/edit/node-apgwgb?file=index.js and run `yarn start`. The first error is logged by the root logger and is nicely reported. The second one, logged by the sub-logger and is broken.

**Expected behavior**
Both errors are logged nicely formatted.

**Comment by terehov** [comment]
Thank you for reporting. I found the problem and fixed it. Was just a type when cloning settings 🤦‍♂️

**Comment by terehov** [comment]
`V4.4.1` fixes this.
