### ISSUE TITLE
Bug: [BUG] Date is wrong

### ISSUE THREAD

**Issue by rhob1** [fullstack-build/tslog#187]
**Describe the bug**
When using own format for date (not "dateIsoStr") the date seems to be wrong. The number for the day is too high.

**To Reproduce**

Use a template and specifiy own format for date e.g. {{yyyy}}-{{mm}}-{{dd}} {{hh}}:{{MM}}:{{ss}}:{{ms}}
When printing a log entry the day part is wrong.

I assume the line 297 in Baselogger.ts causes the problem:

 placeholderValues["dd"] = formatNumberAddZeros(logObjMeta?.date?.getDate(), 2, 1);

formatNumberAddZeros adds 1 to the day which is not necessary I think. So leaving out the 3rd parameter of formatNumberAddZeros might fix this.

**Comment by terehov** [comment]
Thank you. `V4.4.4` will fix it 👍
