### ISSUE TITLE
Feature Request: printing JSON on one line

### ISSUE THREAD

**Issue by tomADC443** [fullstack-build/tslog#191]
If I am right the 3.x version was printing JSON in one line, even stating it in the readme:

> "Hint: Each JSON log is printed in one line, making it easily parsable by external services." 

in the current version 4.4.4 that doesn't seem to be the case anymore. Is it possible to allow that again?

**Comment by quinnturner** [comment]
Added support for configuring the JSON indentation in this PR: #196

**Comment by terehov** [comment]
@tomADC443 Thank you for pointing this out and thank you, @quinnturner, for your PR.

This is definitely slipped through my fingers and shouldn't be the case, undermining the whole point of having JSON logs in the first place.  
_My understanding is the following:_
JSON logs are meant to be read by machines in the first place, so the default output should be without any formatting. 
If you want to format it in any other way than the default `JSON.stringify`, you can always overwrite the `transportJSON ` function. 

So I am going to fix this in V4.5.0 shortly. 

@quinnturner I'll reply to your PR directly in a review. 🙏

**Comment by terehov** [comment]
V4.5.0 is out now.

**Comment by tomADC443** [comment]
Thank you! :D
