### ISSUE TITLE
Bug: Incorrect timezone due to performance fix

### ISSUE THREAD

**Issue by josemmo** [fullstack-build/tslog#198]
**Describe the bug**
When using the default date template `{{yyyy}}.{{mm}}.{{dd}} {{hh}}:{{MM}}:{{ss}}:{{ms}}`, BaseLogger will automatically convert it to `{{dateIsoStr}}`:

https://github.com/fullstack-build/tslog/blob/72088fbcd287aa285d38c7fd259398afb39e8601/src/BaseLogger.ts#L290-L306

However, because `{{dateIsoStr}}` uses the method `Date.prototype.toISOString()`, it will output the formatted date in UTC, regardless of the timezone configuration of Node.js or the browser.

**To Reproduce**

1. Create a new logger with the default settings: `const logger = new Logger()`
2. Add new logs: `logger.info('This is a test')`

**Expected behavior**
The pretty output should print dates in the timezone of the execution environment. However, it always uses UTC.

**Proposed solution**
Create a new placeholder called `{{dateStr}}` that will produce the same output as `{{dateIsoStr}}` but in the system's timezone.
Additionally, support a new `{{tz}}` placeholder to print time timezone offset (e.g., "+02:00", "Z").

**Node.js Version**
Tested on 18.12.1, should be applicable to all Node.js versions.

**OS incl. Version**
Tested on Windows 10 Pro 22H2, should be applicable to any compatible OS.

**Comment by terehov** [comment]
I like your proposal. I'll come up with a solution tomorrow.

**Comment by terehov** [comment]
My idea is to add another setting `prettyLogTimeZone`, which will be "UTC" be default to ensure backwards compatibility and can also be set to "local".
What do you think?

**Comment by terehov** [comment]
So basically like this: 
```typescript

    if (template.includes("{{yyyy}}.{{mm}}.{{dd}} {{hh}}:{{MM}}:{{ss}}:{{ms}}")) {
      template = template.replace("{{yyyy}}.{{mm}}.{{dd}} {{hh}}:{{MM}}:{{ss}}:{{ms}}", "{{dateIsoStr}}");
    } else {
      if (this.settings.prettyLogTimeZone === "UTC") {
        placeholderValues["yyyy"] = logObjMeta?.date?.getUTCFullYear() ?? "----";
        placeholderValues["mm"] = formatNumberAddZeros(logObjMeta?.date?.getUTCMonth(), 2, 1);
        placeholderValues["dd"] = formatNumberAddZeros(logObjMeta?.date?.getUTCDate(), 2);
        placeholderValues["hh"] = formatNumberAddZeros(logObjMeta?.date?.getUTCHours(), 2);
        placeholderValues["MM"] = formatNumberAddZeros(logObjMeta?.date?.getUTCMinutes(), 2);
        placeholderValues["ss"] = formatNumberAddZeros(logObjMeta?.date?.getUTCSeconds(), 2);
        placeholderValues["ms"] = formatNumberAddZeros(logObjMeta?.date?.getUTCMilliseconds(), 3);
      } else {
        placeholderValues["yyyy"] = logObjMeta?.date?.getFullYear() ?? "----";
        placeholderValues["mm"] = formatNumberAddZeros(logObjMeta?.date?.getMonth(), 2, 1);
        placeholderValues["dd"] = formatNumberAddZeros(logObjMeta?.date?.getDate(), 2);
        placeholderValues["hh"] = formatNumberAddZeros(logObjMeta?.date?.getHours(), 2);
        placeholderValues["MM"] = formatNumberAddZeros(logObjMeta?.date?.getMinutes(), 2);
        placeholderValues["ss"] = formatNumberAddZeros(logObjMeta?.date?.getSeconds(), 2);
        placeholderValues["ms"] = formatNumberAddZeros(logObjMeta?.date?.getMilliseconds(), 3);
      }
    }
    const dateInSettingsTimeZone =
      this.settings.prettyLogTimeZone === "UTC" ? logObjMeta?.date : new Date(logObjMeta?.date?.getTime() - logObjMeta?.date?.getTimezoneOffset() * 60000);```

**Comment by terehov** [comment]
V4.6.0 is out with timezone support for UTC and local.
