### ISSUE TITLE
Bug: [BUG] Performance issues

### ISSUE THREAD

**Issue by cipri-p** [fullstack-build/tslog#199]
**Describe the bug**
I've been using this logger in a few lambdas (thanks for sharing it!) and a couple of days ago I started updating my lambdas to use the latest version. I've noticed that a few of them started failing and on a closer look they timed out.  In the new version, it seems that the logger is much slower that it used to be. Some of my lambda (backend for an api) do log quite a bit (around 50 debug messages per call). If I change the logging level to info, my lambdas work as expected since it's not much that gets logged. Same if I use console.log.

**To Reproduce**
Create a lambda function that has a duration of around 5 sec. In your lambda try to log around 50-100 messages.

**Expected behavior**

**Screenshots**
ClooudWatch logs from my lambda using tslog (logger.debug)
![Pasted Graphic](https://user-images.githubusercontent.com/19701425/208642106-38c89b28-505e-48d1-a9fb-4b6478513a96.png)
And same code where I replace the logger with console.log
![Pasted Graphic 1](https://user-images.githubusercontent.com/19701425/208642221-9912a410-43c5-42bf-9de3-ddaae9afc7f5.png)

**Additional context**

**Node.js Version**
e.g. 16.x

**OS incl. Version**
n/a

**Comment by terehov** [comment]
Which versions are you comparing exactly? And how do you implement the logger? 
Please provide an example for reproduction.

**Comment by cipri-p** [comment]
I'm using version 4.4.5. 

Here's my logger:

```import { ISettingsParam, Logger } from 'tslog';
import { ILogObj } from 'tslog/dist/types/interfaces';

enum LogLevel {
  silly,
  trace,
  debug,
  info,
  warn,
  error,
  fatal,
}

 const getLoggerProps = (): ISettingsParam<ILogObj> => {
  return {
    name: 'Service',
    minLevel: LogLevel.debug,
    type: 'pretty',
    stylePrettyLogs: false,
    prettyLogTemplate: '{{logLevelName}} [{{name}}]',
    prefix: [''],
  };
};

export const logger: Logger<ILogObj> = new Logger(getLoggerProps());
```

And then I'll use it:
```
import { logger } from './logger'
...
logger.debug("message to log")
```

**Comment by terehov** [comment]
Thank you for reporting this. 
I am happy to announce the release of V4.7.0, which includes several performance enhancements. One notable improvement is the inclusion of a setting called `hideLogPositionForProduction`, which allows you to disable the localization of the log in the source code for production environments. This feature can significantly improve performance, as it can slow down performance by up to a factor of 10. Please note that this setting is disabled by default, but can easily be enabled as needed.
