### ISSUE TITLE
Bug: Fails in Chrome Extensions

### ISSUE THREAD

**Issue by liaxei** [fullstack-build/tslog#202]
**Describe the bug**
**tslog** fails if used in **Manifest V3 Chrome Extensions**. More specifically it fails in **background pages** which now use **service workers**. The reason is that service workers do not have a **window** object. So the following code in tslog/dist/esm/runtime/browser/index.js fails:
`const meta = {
    runtime: "Browser",
    browser: window?.["navigator"].userAgent,
};`

**To Reproduce**

1. Create a basic Chrome Extension
2. Add **tslog** to a **background** script
3. Load the unpacked extension to your Chrome. To do that turn on the Developer mode on Extensions page.
4. Click on the "background page" link on your extension on Extensions page to open DevTools
5. Check the error in the Console of DevTools

**Expected behavior**
Extension should not fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/10522778/210184084-959c405f-e86b-406b-a52c-3cd61e82b7cd.png)

**Solution**
Use **self** if window is not defined.

**Comment by terehov** [comment]
MR is welcome. 
Otherwise an explanation how to create a basic chrome extension.

**Comment by liaxei** [comment]
@terehov I have created a chrome extension for you to play with https://github.com/liaxei/dummy-chrome-extension

**Comment by terehov** [comment]
Check out `V4.8.0`.
