### ISSUE TITLE
Bug: 4.7.3, no bundled types

### ISSUE THREAD

**Issue by sachaw** [fullstack-build/tslog#215]
latest release breaks typescript support, downgrading to 4.7.2 resolves the issue.

TSC error:
```
error TS2307: Cannot find module 'tslog' or its corresponding type declarations.
```

Another issue that is likely related, is consuming it with vite reports:
```
'Failed to resolve entry for package "tslog". The package may have incorrect main/module/exports specified in its package.json.'
```

**Comment by JoeKarow** [comment]
It looks like only the browser package was built in the latest release.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/58997957/219843874-98e6e35a-108c-47a8-b45e-14c9eeebe5a5.png">

**Comment by terehov** [comment]
Thanks guys. That's strange that the `pre-publish` build didn't run properly. 

`v4.7.4` fixes this.
