### ISSUE TITLE
Bug: `userAgent` is undefined with Cloudflare Workers

### ISSUE THREAD

**Issue by mpint** [fullstack-build/tslog#221]
**Describe the bug**
Hi there, 4.8.1 added [isometric `globalThis`](https://github.com/fullstack-build/tslog/commit/7018919248180458449aa7fb65d7f6dc69c877ff), but `navigator` doesn't exist in the Cloudflare Workers (and Vercel Edge Functions) runtime, so it still breaks.

```
const meta: IMetaStatic = {
  runtime: "Browser",
  browser: globalThis?.["navigator"].userAgent,
};
```

```
import { ILogObj, Logger } from "tslog"
export const logs: Logger<ILogObj> = new Logger()
logs.silly("Running website monitors")
// TypeError: Cannot read properties of undefined (reading 'userAgent')
```
**To Reproduce**

Basic hello-world in Cloudflare Workers

**Comment by terehov** [comment]
Thank you. Check out `V4.8.2`. Does it work now?

**Comment by mpint** [comment]
Thanks for the quick response, but not quite! Now I'm seeing:
```
error TypeError: Cannot read properties of undefined (reading 'origin')
    at stackLineToStackFrame (node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/esm/runtime/browser/index.js:32:38)
    at getCallerStackFrame (node_modules/.pnpm/tslog@4.8.2/node_modules/tslog/dist/esm/runtime/browser/index.js:20:12)
```
It might be worth playing around with https://cloudflareworkers.com to see which globals the runtime provides.

**Comment by OultimoCoder** [comment]
Any update on this?
