### ISSUE TITLE
Feature Request: Easier modification of log messages

### ISSUE THREAD

**Issue by matthewoates** [fullstack-build/tslog#225]
The log message is really verbose, so I'd like to alias `DEBUG`, `INFO`, etc to 3 character abbreviations and use a single space afterwards instead of the `\t`.

basically this:

```
07:12:21:622 DEBUG      [link.ts:140]   Ambiguity found. (values) ff04 vs 6cab
07:12:21:672 INFO       [NodePipeline.ts:139]   saved 1 cheatsheets
07:12:21:685 INFO       [NodePipeline.ts:139]   saved 27 algos
07:12:21:710 INFO       [NodePipeline.ts:139]   saved 118 concepts
07:12:21:715 INFO       [buildDist.ts:29]       🎉 1142 ms DONE 🎉
```

becomes:
```
07:12:21:622 DBG [link.ts:140]   Ambiguity found. (values) ff04 vs 6cab
07:12:21:672 INF [NodePipeline.ts:139]   saved 1 cheatsheets
07:12:21:685 INF [NodePipeline.ts:139]   saved 27 algos
07:12:21:710 INF [NodePipeline.ts:139]   saved 118 concepts
07:12:21:715 INF [buildDist.ts:29]       🎉 1142 ms DONE 🎉
```

I'm having a super hard time figuring out how to do this.

I thought I could use `addMeta` to map the log level to my new names and use that in the template string, but it doesn't seem like I can use meta fields in the template string.

I thought I could modify the `formatLogObj`, but it looks like that just lets me modify the arguments passed into ts-log and the errors.

How can this be done cleanly?

**Comment by terehov** [comment]
Sure, that should be super easy with `tslog 4`, since you can define your own log level and name the as you wish. So basically you just need to extend the `BaseLogger`, like we do it internally. Have a look here: 
https://github.com/fullstack-build/tslog/blob/master/src/index.ts

And with this setting you can change the template, e.g. replace the tab with a single space:
```ts
prettyLogTemplate:  "{{yyyy}}.{{mm}}.{{dd}} {{hh}}:{{MM}}:{{ss}}:{{ms}} {{logLevelName}} {{filePathWithLine}}{{nameWithDelimiterPrefix}}\t",
```
