### ISSUE TITLE
Bug: BaseLogger breaks if Class of logged error has > 1 required constructor arguments

### ISSUE THREAD

**Issue by nickluger** [fullstack-build/tslog#227]
**Describe the bug**
This line assumes that an error constructor has only one required parameter:
https://github.com/fullstack-build/tslog/blob/28ef27ab3ef97b667afc48dea1c98651ef46731e/src/BaseLogger.ts#L280

If that is not the case, this code breaks the invoked error constructor.

**To Reproduce**

```ts
logger.error(new MyErrorWithMultipleRequiredParameters(a, b))
```

**Expected behavior**
I don't know what `_cloneError` is actually doing, but it should respect error constructors that have multiple required parameters, especially if I don't control these. For example the Prisma ORM throws errors with a second required parameter.

**Node.js Version**
v16.18.1

**Comment by nickluger** [comment]
Workaround: Go back to **4.7.4.** This was introduced by https://github.com/fullstack-build/tslog/commit/a5a0ac2e0a4dc6b5ab7840809e70d08dc177d01f

**Comment by terehov** [comment]
Thank you for reporting. 
Would that solve the problem for you? 

This method is used to clone the error object in order safely manipulate the cloned one (especially for masking secrets) without changing the original one. 

```ts
  private _cloneError<T extends Error>(error: T): T {
    const ErrorConstructor = error.constructor as new (...args: any[]) => T;
    const errorProperties = Object.getOwnPropertyNames(error);
    const errorArgs = errorProperties.map((propName) => error[propName]);

    const newError = new ErrorConstructor(...errorArgs);
    Object.assign(newError, error);

    for (const propName of errorProperties) {
      const propDesc = Object.getOwnPropertyDescriptor(newError, propName);
      if (propDesc) {
        propDesc.writable = true;
        Object.defineProperty(newError, propName, propDesc);
      }
    }
    return newError;
  }
```

**Comment by terehov** [comment]
That's exactly the problem here. On the one hand we want to offer secret masking, which in my opinion is essential for logging, on the other hand we don't want to manipulate the original object and therefore need a copy of it and there is no official way of doing so for the error object. 
The commit you mentioned was an attempt to solve this bug, when some properties are read-only: https://github.com/fullstack-build/tslog/issues/217

Have you any thoughts on how to solve this?

**Comment by Mordred** [comment]
For me it breaks for typeorm `QueryFailedError` which expects that `driverError` has `toString()` method in constructor: https://github.com/typeorm/typeorm/blob/master/src/error/QueryFailedError.ts

```
TypeError  Cannot read properties of undefined (reading 'toString')
error stack:
  • QueryFailedError.js	new QueryFailedError
	/node_modules/typeorm/error/QueryFailedError.js:12
  • BaseLogger.js	Logger._cloneError
	/node_modules/tslog/dist/esm/BaseLogger.js:221
  • BaseLogger.js	Logger._recursiveCloneAndMaskValuesOfKeys
	/node_modules/tslog/dist/esm/BaseLogger.js:166
  • BaseLogger.js	
	/node_modules/tslog/dist/esm/BaseLogger.js:140
  • 	
	
  • BaseLogger.js	Logger._mask
	/node_modules/tslog/dist/esm/BaseLogger.js:139
  • BaseLogger.js	Logger.log
	/node_modules/tslog/dist/esm/BaseLogger.js:82
  • index.js	Logger.error
	/node_modules/tslog/dist/esm/index.js:26
  • index.js	Object.didEncounterErrors
	/dist/index.js:249
  • requestPipeline.js	
	/node_modules/@apollo/server/dist/esm/requestPipeline.js:275
```

**Comment by terehov** [comment]
Please check `V4.9.0`.
