### ISSUE TITLE
Storybook not compile with TSLog (NextJS and React) Bug: [BUG]

### ISSUE THREAD

**Issue by hotequil** [fullstack-build/tslog#235]
**Describe the bug**
I'm trying run the Storybook with components using the TSLog, but occurs an error. I tried a lot of configs in `main.js` of Storybook, in my `tsconfig.json` and others things.

**To Reproduce**

1. Run the `start-storybook --ci -s ./public -p 6006` command;
2. Throw the error.

**Expected behavior**
My Storybook should be compile correctly.

**Screenshots**
![Error](https://github.com/fullstack-build/tslog/assets/46814712/0aadf223-f089-4843-b810-f89c664af29d)
![Logger](https://github.com/fullstack-build/tslog/assets/46814712/c1bd399b-c68f-4167-a456-35a05c647a51)

**NextJS Version**
11.1.2

**React Version**
17.0.2

**TSLog Version**
4.8.2

**TypeScript Version**
4.4.3

**Storybook Version**
6.3.10

**Node.js Version**
16.14.0

**OS incl. Version**
Linux Mint 20.2 Cinnamon

**Comment by terehov** [comment]
Can you try with `V4.8.7` please and reopen if it still occurs. thx.
