### ISSUE TITLE
formatWithOptions is Undefined: [BUG]

### ISSUE THREAD

**Issue by mihirgarg01** [fullstack-build/tslog#238]
**Describe the bug**
Upon running the example code for tslog, I recive an error:  'TypeError: formatWithOptions is not a function.'
Here's the entire error: [pastebin.com](https://pastebin.com/asvfqH4U)

**To Reproduce**
1. Use bunjs v0.6.8
2. Install tslog
3. Create a file called logger.ts
4. Use example code found from [readme.md](https://github.com/fullstack-build/tslog#readme)
5. In WSL, run `bun run logger.ts`
6. See error in console

**Expected behavior**
"Hello World" should have been returned in the console.

**Screenshots**
[Code & Error](https://imgur.com/JwjbWSa)

**Additional context**
I am using bunjs, not nodejs. Entirely possible that's the issue.

**Node.js Version**
Bunjs 0.6.8

**OS incl. Version**
Ubuntu 22.04.2 LTS on WIndows 10

**Comment by drewbitt** [comment]
Bun encourages opening issues with Bun when libraries fail. It the mission of Bun to be node library compatible.

**Comment by terehov** [comment]
Seems like it's an issue with bun and `formatWithOptions` is not supported yet. 

Have a look: 
https://bun.sh/docs/runtime/nodejs-apis

>[node:util](https://nodejs.org/api/util.html)

🟡 Missing util.MIMEParams util.MIMEType util.formatWithOptions()...

**Comment by mgcrea** [comment]
This has been fixed with `bun@1.1.0` and is now working, see https://bun.sh/docs/runtime/nodejs-apis#node-util.
