### ISSUE TITLE
Bug: null value logs as undefined

### ISSUE THREAD

**Issue by dever23b** [fullstack-build/tslog#242]
**Describe the bug**
TSLog writes null values as undefined.  It severely threw off my troubleshooting of an unrelated bug in my project.

**To Reproduce**

```typescript
const testObj = { true: true, false: false, null: null, undefined: undefined };
console.debug('Testing [console]', testObj);
log.debug('Testing [tslog]', testObj);
```

> Testing [console] {true: true, false: false, null: null, undefined: undefined}
> index.js:81 2023-07-09 05:09:32.911	DEBUG		TestComponent	Testing [tslog] {
>   true: true,
>   false: false,
>   null: undefined,
>   undefined: undefined 
> }

**Expected behavior**
Correct values to be displayed when an object is logged

**Comment by terehov** [comment]
Works in `V.4.8.7`

<img width="580" alt="Screenshot 2023-08-07 at 23 05 18" src="https://github.com/fullstack-build/tslog/assets/490885/6e8f3d68-9fda-4a90-bdfd-d681231a7c3c">

**Comment by dever23b** [comment]
That's also how I discovered the bug too, unfortunately.

**Comment by vktrl** [comment]
Looks like it's only happening in the browser because of a polyfill. Opened a pull request with a fix and additional tests.

**Comment by terehov** [comment]
Thank you. I'll check and merge it tomorrow.

**Comment by terehov** [comment]
`V4.9.2` is out. thank you for this MR.
