### ISSUE TITLE
Documentation: README.md suggest to import `ILogObjMeta` but it is not exported by the package

### ISSUE THREAD

**Issue by BenceSzalai** [fullstack-build/tslog#243]
**Describe the bug**
Sorry, might not be a bug, maybe only needs clarification in the documentation (or my head).

So I was trying to add custom log level based on [this section of the README](https://github.com/fullstack-build/tslog#custom-log-level).

However importing from `"./BaseLogger"` would only make sense if someone was forking the library and adding the `CustomLogger` to the original codebase. Indeed when used in a project it would be more common (if not exclusive) to try to import stuff from `node_modules` using `import { /*...*/ } from 'tslog'`. However to me it appears that `ILogObjMeta` is not exported as part of `'tslog'`

I have worked it around this way:
```typescript
export class CustomLogger<LogObj> extends BaseLogger<LogObj> {
  /*...*/
  public custom ( ...args: unknown[] ): ReturnType<BaseLogger<LogObj>['log']> {
    return super.log( 8, 'CUSTOM', ...args )
  }
}
```

But I'm thinking that maybe I'm missing the real meaning of the givend README section or it may need to be adjusted...?

**Comment by terehov** [comment]
Fixed in `V4.8.7`
