### ISSUE TITLE
Question about filepaths

### ISSUE THREAD

**Issue by ItzMarni** [fullstack-build/tslog#248]
This logger produces a file path from the users directory which I assume is a bug? or some weird feature, anyway this can be changed the the project root/src folder?

**Comment by terehov** [comment]
Is should not be from the user directory but rather from the main directory of the project. And yes, you can change that by using {{fullFilePath}}. 
Please check the docs: 
https://tslog.js.org/#/?id=pretty-templates-and-styles-color-settings
