### ISSUE TITLE
Documentation: README.md suggest a broken way to extend `BaseLogger`

### ISSUE THREAD

**Issue by BenceSzalai** [fullstack-build/tslog#256]
**Describe the bug**
The documentation [here](https://github.com/fullstack-build/tslog#custom-log-level) suggests to extend `BaseLogger` as:
```typescript
export class CustomLogger<LogObj> extends BaseLogger<LogObj> {
  constructor(settings?: ISettingsParam<LogObj>, logObj?: LogObj) {
    super(settings, logObj, 5); // not valid any more
  }
}
```

However since [v4.8.3](https://github.com/fullstack-build/tslog/compare/v4.8.2...v4.8.3) `constructor` of `BaseLogger` was changed to include a new first parameter `runtime`.

What is the recommended way to extend the logger now?

**Comment by BenceSzalai** [comment]
I guess the README could be upgraded to:
```typescript
import { BaseLogger, Runtime } from 'tslog'

export class CustomLogger<LogObj> extends BaseLogger<LogObj> {
  constructor(settings?: ISettingsParam<LogObj>, logObj?: LogObj) {
    super(Runtime, settings, logObj, 5);
  }
}
```

**Comment by BenceSzalai** [comment]
Also this part is broken now:
```typescript
  public custom(...args: unknown[]): LogObj & ILogObjMeta {
    return super.log(8, "CUSTOM", ...args);
  }
```
because `BaseLogger` `log` method is declared to have a return type of `(LogObj & ILogObjMeta) | undefined` instead of `LogObj & ILogObjMeta` since https://github.com/fullstack-build/tslog/commit/7f0670e3f3c2657aaa91f09b9ede296d5c09c7f3 .

**Comment by terehov** [comment]
Thank you for pointing this out. You're right. I'll update the docs.

**Comment by terehov** [comment]
To be honest, it shouldn't have happened, especially since it was just a minor update. I must have overlooked that during a PR merge. Sorry about that. 
I moved the runtime into the BaseLogger, so the API can remain the same. I will release a patch shortly.

**Comment by terehov** [comment]
Solved in `V4.9.1`.

**Comment by BenceSzalai** [comment]
Probably should have opened a separate issue, but I thought both were about updateing documentation. So the part about `public custom(...args: unknown[]): LogObj & ILogObjMeta {` is still invalid.

**Comment by terehov** [comment]
Thank you, I updated the docs: 

[98191886](https://github.com/fullstack-build/tslog#custom-log-level)
