### ISSUE TITLE
json loging api: [Feature]

### ISSUE THREAD

**Issue by tomer-refundit** [fullstack-build/tslog#26]
when log output is json add option to to log json object
for example
logger.info({userId: 123})

expected output: 
{
//...
userId: 123
}

current output:
{
//...
argumentsArray:[{userId: 123}]

**Comment by terehov** [comment]
Hi @tomer-refundit,

I understand where you're coming from, the question is: what should be a sane default. 
You can pass multiple attributes to each log message, so there has to be an array and you also want the meta-information. 
May I point you to a direction: 
If I understand correctly your use case, you only have one object as an attribute and are therefor nit interesting in the other attributes, plus you're not interested in the meta-information. 

In such a use case you could attach a custom transport (https://github.com/fullstack-build/tslog#transport) and transform `ILogObject` into what you want it to look like and print it to `StdOut`. So `tslog` should be flexible enough here already. 

So the only thing I could add is a third type `hidden`, to prevent `tslog` from printing at all. 

Would that be a suitable solution for your use case?

**Comment by tomer-refundit** [comment]
Hi @terehov 
I have a suggestion.
when the argument type is object and not error and the output is json merge the argument with ILogObject.

**Comment by terehov** [comment]
Sorry, but this doesn't seem to be a good API design, nor follow clean code. You would end up with a messed up interface, and a functionality doing some magic when you don't expect it. Just a simple example: 
```
log.info({foo: "bar"});
log.info("foo", "bar");
```
These two lines would behave completely differently. 

What are your thoughts about my suggestion to use a custom transport in a combination with `type: "none"`. Wouldn't that solve your problem?

**Comment by tomer-refundit** [comment]
@terehov your solution will work. thanks
of course this 2 line with behave differently. in one you log 2 string and in the other one you log object.

but i think in the long run if this logger is really want to be also a json logger, then logging object should be natural.

about the interface and clean code, do you accept PRs?

**Comment by terehov** [comment]
Yes, of course, I would be happy to review your suggestion.

**Comment by terehov** [comment]
There is a detail that I forgot to mention earlier that you should consider:
When you try to print a log, it will be converted from `ILogObject` into `ILogObjectStringifiable` and all the attributes will be "inspected" with `util.inspect`, so `argumentsArray` is not an array of the original objects anymore but converted into strings. 
There are two main reasons why `util.inspect` is used instead of `JSON.stringify`:
- JSON is a very limited subset of JS and there are many things that go missing like Symbols, Functions, BigInts...
- Circular structures

**Comment by terehov** [comment]
I have just released a new version with new `type:hidden` that should help you with this use case. 

https://github.com/fullstack-build/tslog/releases/tag/v2.6.0
