### ISSUE TITLE
Customizing field names for arguments using `type:json`

### ISSUE THREAD

**Issue by mblockk** [fullstack-build/tslog#261]
Is it possible? For example, instead of the output being
```
{
   0: firstArg,
   1: secondArg
}
```

I'd like to have something like 
```
{
   msg: firstArg,
   custom1: secondArg,
   ...
   customN: NthArg
}
```

Apologies if this is discussed elsewhere; I've taken a look and didn't see it.

**Comment by terehov** [comment]
Yes, you can do this with overwrites: 

https://tslog.js.org/#/?id=overwriting-default-behavior
