### ISSUE TITLE
Feature Request: [Feature]

### ISSUE THREAD

**Issue by FreePhoenix888** [fullstack-build/tslog#264]
**Description / Use Case for a Feature**

Add possibility to extend name.

I wanted to use this library instead of `debug` library which can extend namespaces. For some reason there is no such possibility. Why?

**Comment by terehov** [comment]
Can you elaborate what you exactly mean? Thank you

**Comment by FreePhoenix888** [comment]
> Can you elaborate what you exactly mean? Thank you

What I can do when I use debug library:
```
import _debug from debug
const debug = _debug("myPackageName")
const moduleDebug = debug.extend("myModuleName")
const moduleLog = debug.extend('log')
const moduleError = debug.extend('error')
```

**Comment by terehov** [comment]
You can already do this with https://tslog.js.org/#/?id=sub-logger

**Comment by FreePhoenix888** [comment]
Thank you, @terehov !
