### ISSUE TITLE
Tauri Webview do not show a correct format

### ISSUE THREAD

**Issue by realtica** [fullstack-build/tslog#277]
Tauri Webview do not show a correct format, please see the image:

![image](https://github.com/fullstack-build/tslog/assets/852446/b4bd6a26-bd7d-4c3a-945d-b86902000ac9)

In a Web browser all working well:
![image](https://github.com/fullstack-build/tslog/assets/852446/18d58091-be98-455b-97d0-83522f8a47b4)

What could be happening?

**Comment by terehov** [comment]
What you see are ANSI ESC Codes. They are used to style the output. We try to detect whether the systems supports them or not. But you can also manually disable them: `stylePrettyLogs: false`

https://tslog.js.org/#/?id=pretty-templates-and-styles-color-settings

**Comment by realtica** [comment]
> What you see are ANSI ESC Codes. They are used to style the output. We try to detect whether the systems supports them or not. But you can also manually disable them: `stylePrettyLogs: false`
> 
> https://tslog.js.org/#/?id=pretty-templates-and-styles-color-settings

Thanks!, simple values shows well, but (arrays) brackets do not.. what can do I?![image](https://github.com/fullstack-build/tslog/assets/852446/1c35b39b-3668-4bf7-a746-2a501fbed115)

**Comment by wsw70** [comment]
> What you see are ANSI ESC Codes. They are used to style the output. We try to detect whether the systems supports them or not. But you can also manually disable them: `stylePrettyLogs: false`
> 
> https://tslog.js.org/#/?id=pretty-templates-and-styles-color-settings

Is it possible to differentiate logs intended for the front vs the back (back is OK, front is not interpreted) (short of making two loggers of course)
