### ISSUE TITLE
GraphQL JSON Parse error: Unrecognized token '<' error when using TSLog library

### ISSUE THREAD

**Issue by paul590** [fullstack-build/tslog#31]
Hello,

I am currently running into an issue where upon adding a log using this library, my graphql query errors stop working and return the following error: JSON Parse error: Unrecognized token '<'. This only affects when i am expecting graphql to return an error, i am able to get data when i am expecting data. I am using apollo-server and graphql with this library. 
I added the following parameters:
export const logger = new Logger({ minLevel: "debug", displayDateTime: true, dateTimeTimezone: "America/New_York", name: "console", overwriteConsole: true });

If more information is required please let me know. Thank you for your help!

**Comment by terehov** [comment]
Hey @paul590 

Which version of tslog do you use?

**Comment by paul590** [comment]
Hi @terehov thank you for getting back to me. I am using version 2.6.1

**Comment by terehov** [comment]
Great! To help me analyze this issue: would you be able to extract this problem into a small repo, which I can use to reproduce this issue and where I could see the exact dependencies with their versions in package.json

That would be highly appreciated!

**Comment by terehov** [comment]
@paul590 Do you still experience this problem? I wasn't able to reproduce it. 
I am going to close this issue due to inactivity. Should this be an ongoing problem, I would kindly ask you to open a new issue.
