### ISSUE TITLE
Bug: stack trace error

### ISSUE THREAD

**Issue by deman4ik** [fullstack-build/tslog#34]
**Describe the bug**
After updating to 2.6.1 I got error in bluebird

`/node_modules/bluebird/js/release/debuggability.js:768
    var lastStackLines = (lastLineError.stack || "").split("\n");`

seems like tslog converts error.stack into array

**To Reproduce**
```js
const { Logger } = require("tslog");
const promise = require("bluebird");

const logger = new Logger();

async function run() {
    try {
        await promise.any([Promise.resolve()]);
    } catch (err) {
        logger.error(err);
    }
}
run();
```

**Additional context**
Node.JS 12.18.0
tslog ^2.6.1

Seems related #33

**Comment by terehov** [comment]
Thank you. Once again a great bug report. I am going to looking into it now.

**Comment by deman4ik** [comment]
@terehov Unfortunately that doesn't fix the problem.
Please try to run reproduction code with just node without ts. Error only appears in compiled js version, but with ts-node works fine.

**Comment by terehov** [comment]
I did and seemed to work. I’ll give it another try tomorrow morning. Sorry about that.

**Comment by deman4ik** [comment]
@terehov 
I think you forgot to build npm package properly 
`dist/src/CallSitesHelper.js` contains latest fix but `dist/CallSitesHelper.js` don't
![Screenshot 2020-07-17 at 03 27 07](https://user-images.githubusercontent.com/913027/87735194-83bb2000-c7dd-11ea-8df8-2e90d832ef9b.png)

**Comment by terehov** [comment]
Good hint, thx. 
I did build it, however, I added examples into the build and that created nested folders (`src` inside of `dist`). 
A new version is on its way. Sorry about that.

**Comment by terehov** [comment]
Please give `v2.6.3` a try.

**Comment by deman4ik** [comment]
@terehov Works fine now. Thank you.
