### ISSUE TITLE
Bug: [BUG]

### ISSUE THREAD

**Issue by pegasuspect** [fullstack-build/tslog#37]
**Describe the bug**
TSLog masks password only if it is the last value in the json.

**To Reproduce**
1. `mkdir tslogBugReplace`
2. `cd tslogBugReplace`
3. `npm init -y`
4. `npm i tslog`
5. Open directory with your favourite text editor and create **index.js**
6. Run the following code:
```js
const { Logger } = require('tslog');
let log = new Logger();

log.info({ password: 'topsecret', user: 'test'});
// password is masked.

log.info({ user: 'test', password: 'topsecret' });
// password is not masked!

log.info({ user: 'test', password: 'topsecret', iWillMask: 'Because I exist' });
// Whew! It's masked again.
// Hint: util.inspect() does not add a comma after the last key in json.

// In the following example:
// Keys do not include password. 
// Only values have the keyword 'password' (case insensitive).
log.info({ 
  errorCode: 'WrongPasswordOrEmail', 
  message: 'Email or Password is wrong! Password, password, password!',
  anyKey: 'any value' // removing this key will result in unmasked message.
});
```
7. `node index.js` or you can also see the screenshot below.

**Expected behavior**
Password should be masked regardless of the comma at the end when it was serialized for replacement with the mask string.

**Screenshots**

<img src="https://i.imgur.com/Trytdin.png"/>

**Additional context**
I have seen the code for replacing the value of the key is using inspect from util library. A simple regex matching for every key-value pair is a bit hard to write. I am currently working on a depth first search approach, where each property is visited and modified then copied to a clone until a cycle is encountered. Finally I would call util.inpect() on the clone as well, and modify the result for pretty printing.

**Comment by terehov** [comment]
Thank you for your great bug report. I am going to release a fixed version shortly.

**Comment by terehov** [comment]
I have released a new version `2.6.4` that addresses this issue. 
Finally, there was only one question mark (?) missing in the RegEx. Thanks for pointing that out. 
Additionally, your screenshot indicated another problem with that RegEx that I also resolved. 
Your output should now look like this: 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/490885/89739938-8d0e7400-da8d-11ea-9097-f77e4c6e39ad.png">

>I am currently working on a depth first search approach, where each property is visited and modified then copied to a clone until a cycle is encountered. Finally I would call util.inpect() on the clone as well, and modify the result for pretty printing.

I understand your point, however, masking happens for each and every log message and running a recursive search would lead to lower performance. `util.inspect` is quite optimized when used once.

**Comment by pegasuspect** [comment]
Great job on fixing this with minimal code. I agree with you about the lower performance. 

However there is one more issue about this, when the json is say:
```js
{ 
  password_hash: 'secret',
  password_column: "love <3"
}
```
The output is:
```sh
{
  password: '[***]',
  password: '[***]',
}
```
Output truncates the password* key into password, showing a different key. It's also invalid json because of the repeated key.

**Comment by terehov** [comment]
Well caught. 

Another patch is on its way. Should look like this: 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/490885/89743368-5e06fb00-daab-11ea-8bff-7e52a795a39f.png">

> It's also invalid json because of the repeated key.
Btw. it's not JSON anyways. JSON is a very limited representation of JS and many types are missing (e.g. BigInt). From the documentation: 

>The util.inspect() method returns a string representation of object that is intended for debugging. The output of util.inspect may change at any time and should not be depended upon programmatically.
[util.inspect(object[, options])](https://nodejs.org/api/util.html#util_util_inspect_object_options)

**Comment by terehov** [comment]
`2.6.5` is released.
