### ISSUE TITLE
Bug: About maskStrings parameter

### ISSUE THREAD

**Issue by pegasuspect** [fullstack-build/tslog#40]
**Describe the bug**
When maskStrings parameter is used tslog is masking the keys as well and also adding an extra colon. Also the maskStrings works case sensitive unlike maskValuesOfKeys. See the screenshot below.

**To Reproduce**
1. `mkdir tslogBugMaskStrings`
1. `cd tslogBugMaskStrings`
1. `npm init -y`
1. `npm i tslog`
1. Create a js file called index.js, `touch index.js` perhaps
1. run the following code:
```js
const { Logger } = require('tslog');
let log = new Logger({
  maskStrings: ['password'],
  maskValuesOfKeys: ['password', 'password_hash']
});

log.info({ 
  password: 'password',
  password_hash: 'hush-hush-hush',
  paSSword_column: "pass Pass password."
});
```

**Expected behavior**
There should be one colon after the key and if it is not intended, keys should not be masked.

**Screenshots**
<img src="https://i.imgur.com/AHv39jj.png" />

**Additional context**
I added this as a separate issue to keep things cleaner with issue #37

**Comment by terehov** [comment]
Hi @pegasuspect, 

thanks again and I appreciate a new issue. 
Double colon is obviously a mistake I added yesterday, however, masking of "all" strings is by design. 
My thought was: A password should not be a "password" but rather a random `string` (e.g. `kff538dd.hgdKJGhfn`) and if you tell `tslog` to mask it, it should be masked everywhere no matter where it appears. 

I would appreciate to hear you thoughts on this.

**Comment by pegasuspect** [comment]
I think its OK to maskStrings either way, the only thing is it must be made obvious in the documentation what it does. Like you explained you might add: It will also mask *keys* if it encounters this random string. 

The naming of the parameter could also help in understanding it. maskStrings is a little general name. It might be *maskAllOccurances*, or if you wanna keep it short *maskAny*. Because when you say strings to me it means literal json string type, as if its not gonna work with number. To somebody else it might mean different as well.

**Comment by terehov** [comment]
Thank you @pegasuspect for your valuable input. I also believe that this name is misleading and have therefore decided to rename it and also clarify in the documentation. 

I have just released a new `next` version. You can give it a spin and tomorrow I'll release as a new minor

`npm i tslog@next`
