### ISSUE TITLE
Bug: TypeError: Cannot read property 'isNative' of undefined

### ISSUE THREAD

**Issue by leolara** [fullstack-build/tslog#46]
**Describe the bug**
I get an error: [TypeError: Cannot read property 'isNative' of undefined] when using the library

**To Reproduce**

In electron environment:
console.log('quicktest')
try {
    const log: Logger = new Logger()
    log.silly('I am a silly log.')
  } catch (e) {
    console.log(e)
  }
console.log('quicktest')

get output:

quicktest
[TypeError: Cannot read property 'isNative' of undefined]
quicktest

**Expected behavior**
Not getting an error

**Additional context**
I am using electron, and running this in the main process

**Comment by leolara** [comment]
I tested this in versions v2.7.1 and v2.8.0 and it happens in both

**Comment by leolara** [comment]
Running it in the browser process of electron get the same error.

Using the debugger it goes to source-map-support dependency to function wrapCallSite, it tries to call frame.isNative() and that seems to be undefined in electron

**Comment by leolara** [comment]
I see that in _buildLogObject relevantCallSites is returned as an empty array, and then it is assumed in the call to wrapCallSite that it has at least one element

**Comment by terehov** [comment]
Hey @leolara, thank you for your bug report. 

Just to clarify: Is `tslog` running in a Node.js context? 

One of the key benefits of `tslog` is it's integration into Node.js and V8 (e.g. for stack traces). Therefore it is a Node.js-only  logger for now. I Have plans to create a client-facing version at some point.

**Comment by leolara** [comment]
Electron is Node. I am 100% sure because I am using the "net" for TCP/IP sockets standard library that obviously you cannot use in a browser environment

**Comment by terehov** [comment]
Alright, I got confused by this: 
> Running it in the browser process of electron get the same error.

Let me try to recreate this issue and get back to you.

**Comment by leolara** [comment]
Electron can run browser processes, but they have access to node libraries. That way they allow to have desktop apps using web technologies. Of course, this must be an electron incompatibility, as it seems

**Comment by terehov** [comment]
I just quickly started their quick start example and it seems to work fine.
Which versions do you use? 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/490885/93182965-0eb78880-f743-11ea-9b81-5136bd605afa.png">

**Comment by leolara** [comment]
I eventually had to switch to winston for the project, which works, as I do not have time to research this
