### ISSUE TITLE
Bug: Can not run debug a script with tslog in vscode

### ISSUE THREAD

**Issue by tjoskar** [fullstack-build/tslog#47]
**Describe the bug**

I'm not sure this is a issue in this lib or if the issue is with vscode debugger. But when I debug a script with tslog in vscode I get the following error:
```
Process exited with code 1
Uncaught Error: write EPIPE
Emitted 'error' event at: <node_internals>/internal/errors.js:463
```

**To Reproduce**

1. Create a new project
```
$ mkdir tslog-test
$ cd tslog-test
$ npm init -y
$ npm install tslog
```
2. Create a new javascript file and name it `test.js`:
```js
const { Logger } = require('tslog');

const logger = new Logger();

logger.error('Hello');
console.log('The end');
```
3. Create a launch.json file by following the GUI guide or create a new file and place it in `.vscode/launch.json`:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/test.js"
    }
  ]
}
```
4. Open the debug panel in vscode och click on "Launch Program" and see the error in "DEBUG CONSOLE".

However, if I execute the script without a debugger it works fine:
```
$ node test.js
2020-09-16 10:46:16.834	 ERROR 	[test.js:5]  	  	Hello
The end
```

And it works also fine with nodes builtin debugger:
```
$ node inspect test.js
< Debugger listening on ws://127.0.0.1:9229/df1e3c02-dc43-40af-83f5-0cd1bc9c534f
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
Break on start in test.js:1
> 1 const { Logger } = require('tslog');
  2
  3 const logger = new Logger();
debug> c
< 2020-09-16 10:47:29.536
<  ERROR
< [test.js:5]
< Hello
< The end
< Waiting for the debugger to disconnect...
debug>
```

**Expected behavior**
I expected to be able to use VScodes debugger with tslog.

**Node.js Version**
e.g. 12.8.0

**OS incl. Version**
macOS 10.15.6

**Comment by terehov** [comment]
Thank you for quite a detailed report. I am going to try and reproduce it.

**Comment by terehov** [comment]
Thank you for hanging in!

I didn't get an error, however, nothing showed up in the debug console:

<img width="1236" alt="Screenshot 2020-09-21 at 11 03 22" src="https://user-images.githubusercontent.com/490885/93744170-1327e980-fbfa-11ea-84fa-c69f7236eee7.png">


So I did some research and found this thread: 
https://github.com/microsoft/vscode/issues/19750

Apparently you have to add these lines: 
```
        "console": "internalConsole",
        "outputCapture": "std"
```

So in your case the whole file would look like this: 
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceFolder}/test.js",
        "console": "internalConsole", 
        "outputCapture": "std"
      }
    ]
  }
  
```

Result: 

<img width="1236" alt="Screenshot 2020-09-21 at 11 06 08" src="https://user-images.githubusercontent.com/490885/93744421-7a459e00-fbfa-11ea-8f63-380942f0d34c.png">

**Comment by terehov** [comment]
@tjoskar Did it solve your problem?

**Comment by tjoskar** [comment]
@terehov Thanks for looking into this. I don't know if this was solved in the latest version of vscode or if a reboot of my computer did the trick or what it was, but it works now and with the extra config lines you suggested above I can see the message in the console as well. Thanks!
