### ISSUE TITLE
Feature Request: React-Native

### ISSUE THREAD

**Issue by whalemare** [fullstack-build/tslog#50]
I try to use your library in my react-native project.

After `yarn add tslog` and use it in project, I have an errors like:

```
Unable to resolve module `os` from `node_modules/tslog/dist/index.js`
```

I suppose, that this `os` module is node based dependency. In react-native we can not access to node features. Can you adapt your library to use it specific environment, like react native?

**Comment by terehov** [comment]
Thank you for your request. 
A big advantage of `tslog` is it’s deep integration into Node.js and V8 and therefore it’s unfortunately not possible to adopt it to other environments. 
That being said, I am planning to create a new, yet compatible library for client side usage. 
However, I don’t have a timeframe for that. 

Any contribution is appreciated :-)
