### ISSUE TITLE
[Question] displayFilePath/displayFunctionName in a "facade" class

### ISSUE THREAD

**Issue by GreenMonkeyBoy** [fullstack-build/tslog#54]
Hello, I have a class `LoggerService`:

```
import { Logger } from 'tslog'

class LoggerService {
  private logger: Logger

  construtor() {
    this.logger = new Logger()
  }

  error(...args) {
    this.logger.error(args)
  }
}
```

Now if I call `error()` somewhere in another file:
```
// app.ts
startApp() {
  this.loggerService.error('something is wrong')
}
```

The settings `displayFilePath` and `displayFunctionName` shows:
```
2020-10-24 16:18:18.210  ERROR  [src/core/logger/logger.service.ts:105 LoggerService.error]             something is wrong 
```
I'd like the log to show:
```
2020-10-24 16:18:18.210  ERROR  [src/app.ts:35 app.startApp]             something is wrong 
```

So my question is can I do something to say "take the file name and function name from the parent class `App` instead of `LoggerService`?

For the stack, I can remove the first item of the array, I wonder if something similar could be done.

**Comment by terehov** [comment]
That’s a very valid request, indeed. 
There is an internal configuration called `_ignoreStackLevels` which is not exposed yet. I gonna put it into the settings and release a new version shortly.

**Comment by terehov** [comment]
Added, going to update docs soon. 
https://github.com/fullstack-build/tslog/releases/tag/v2.11.0
