### ISSUE TITLE
[Question]: disable all colors in `prettyPrintLog`

### ISSUE THREAD

**Issue by kwonoj** [fullstack-build/tslog#55]
**Description / Use Case for a Feature**

If I read correctly, it looks like few cases colors are always applied, such as `dateTime` or `logLevels`: 

- https://github.com/fullstack-build/tslog/blob/d06fc6e1158e350d0f37caa2fd3ceaa3005f1d05/src/index.ts#L542
- https://github.com/fullstack-build/tslog/blob/d06fc6e1158e350d0f37caa2fd3ceaa3005f1d05/src/index.ts#L552

I'm curious if there's way to disable all colors entirely when using `prettyPrintLog`.

Context: I'm trying to write pretty printed output into files, looks like

```
function transport(logObject): {
  logger.prettyPrintLog(fileWriteStream, logObject)
}
```

and it always ends up printing out color code in log output like

```
[90m10/28/2020, 22:54:32:930.000	[39m[1m[0m INFO [0m[22m	
```

Having colors in stdout is still preferred - hope if there's way to have strings without color only for certain cases. Originally I thought creating child logger turns off all colors would allow to use `prettyPrintLog` without colors, but seems like there's no such option unless I miss something.

**Comment by terehov** [comment]
Thank you for this input, @kwonoj,

last few days have been a bit busy. I can totally understand your request and going to add it shortly. 

cheers

**Comment by terehov** [comment]
Added: https://github.com/fullstack-build/tslog/releases/tag/v2.11.0

**Comment by fuhrmanator** [comment]
For some reason, my code won't compile in TypeScript with 

```
export const logger = new Logger({ name: "myLog", minLevel: 3, colorizePrettyLogs: false});
```

How does one set the option to turn off colors?

**Comment by fuhrmanator** [comment]
Sorry for the noise - `stylePrettyLogs: false` works.
