### ISSUE TITLE
Bug: [BUG] Unhandled exception in `_maskValuesOfKeys`

### ISSUE THREAD

**Issue by kwonoj** [fullstack-build/tslog#59]
**Describe the bug**

With latest release, there are some unhandled exception being thrown like below:

```
exceptionStack: 'TypeError: Cannot set property devToolsWebContents of #<BrowserWindow> which has only a getter\n' +
    '    at C:\\github\\apps\\dist\\main.bundle.js:147454:30\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Function.traverseObjectRecursively (C:\\github\\apps\\dist\\main.bundle.js:147445:26)\n' +
    '    at Function.logObjectMaskValuesOfKeys (C:\\github\\apps\\dist\\main.bundle.js:147467:29)\n' +
    '    at Logger._maskValuesOfKeys (C:\\github\\apps\\dist\\main.bundle.js:148020:44)\n' +
    '    at Logger._inspectAndHideSensitive (C:\\github\\apps\\dist\\main.bundle.js:148013:35)\n' +
    '    at C:\\github\\apps\\dist\\main.bundle.js:147911:26\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Logger.printPrettyLog (C:\\github\\apps\\dist\\main.bundle.js:147899:34)\n' +
    '    at Object.writer (C:\\github\\apps\\dist\\main.bundle.js:161187:21)',
```

looks like introduced with https://github.com/fullstack-build/tslog/commit/a80f4a4c596e05db7dccc9a1edeb24e75fe66c76. Assuming traverse tries to mutate given object payload somehow.

**To Reproduce**

clone https://github.com/kwonoj/tslog-getter-exception, `npm ci && npm start`

**Expected behavior**

**Screenshots**

**Additional context**

Though this repro is written in electron, I suspect this could happen in plain node.js usecases. Electron's picked up as it was quickest way to find object have setter restriction while I work with.

**Node.js Version**

**OS incl. Version**

**Comment by kwonoj** [comment]
Tried few and I think best way is do `cloneDeep` against given payload object before traverse it, like using `lodash`'s clonedeep or similar. It looks like given object is being mutated each time logger try to traverse it.

**Comment by terehov** [comment]
Give it a try :-) 

https://github.com/fullstack-build/tslog/releases/tag/v2.11.1
