### ISSUE TITLE
Feature Request: [Feature] tree-shakable dist output support

### ISSUE THREAD

**Issue by kwonoj** [fullstack-build/tslog#61]
**Description / Use Case for a Feature**

This is feature request to support `module` field in package.json allows bundler can pick up tree-shakable code. Whole size of tslog itself is relatively small enough, but I hope tslog could expose import paths to skip few deps like `source-map` as well to squeeze size: it may possible by having export site in top level export (index.ts), but should be esm syntax to allow tree shaking.

Below's size composition for tslog which source-map takes more than half.
![image](https://user-images.githubusercontent.com/1210596/98750974-0c089680-2374-11eb-9e55-230b49b8e8b5.png)

I do not have a strong opinion if it should be true esm or cjs output with esm syntax only - but given native esm support is not wide enough yet, native esm could wait longer. 

Happy to try PR if you don't mind.

**Comment by terehov** [comment]
Of course, you're more than welcome to join. Every PR is highly appreciated 👍

**Comment by terehov** [comment]
@kwonoj So with tree-shaking support we can now reduce the bundle size by half, however, when in a regular Node.js scenario we actually doubled it by delivering esm as well as cjs (effectively blowing up node_modules). 
What do you think about that? 
<img width="420" alt="Screenshot 2020-11-12 at 21 44 56" src="https://user-images.githubusercontent.com/490885/98988576-8847d900-2530-11eb-8cfa-142dbe8bfc24.png">

<img width="400" alt="Screenshot 2020-11-12 at 21 45 08" src="https://user-images.githubusercontent.com/490885/98988566-841bbb80-2530-11eb-8dcf-7715567613b2.png">

**Comment by kwonoj** [comment]
We got similar q also around https://www.npmjs.com/package/rxjs - you can see it's about 5MB, since we ship cjs / esm / esm5(!) / umd + source files to allow declaration map features. Conclusion we had is gain was larger than bytesize, esp it doesn't have lot of transitive dependencies and sole 5MB is something acceptable. Worth to note is even though bytesize itself has grown, cjs user will not import esm in any case - so there's near-0 runtime cost being added into.

But again, this is my personal opinion.

**Comment by terehov** [comment]
Thank you for your input, sounds reasonable to me. I might add something into docs mentioning that.
