### ISSUE TITLE
Feature Request: [Feature] Consistent formatting + timestamp customization for floating point

### ISSUE THREAD

**Issue by kwonoj** [fullstack-build/tslog#63]
**Description / Use Case for a Feature**

1. Space / tab mixed formatting:

![image](https://user-images.githubusercontent.com/1210596/99432545-2a651980-28c1-11eb-8b35-6acda9556aa1.png)

If logger contains different `display` configs across log object as above - for example `displayLogname: true` then some other properties are not set - properties are substituted as space then each separator uses tab. This mixes spaces / tab for output, as well as it'll have numbers of tab instead of single tab separator. 

Curious if it's possible logger do not emit separator for property not to display and have consistent (preferably single tab) separator?

2. floating point customization

It looks like `ms` point is fixed to 3 always, and it's usually not very much helpful as most of log may need ms only. Will it be possible to allow customization for this as well?

**Comment by terehov** [comment]
I have just released a new version as `next` including these changes: 

1. I hope I was able to eliminate all of them. 
2. Additional Zeros are gone now. 

https://github.com/fullstack-build/tslog/releases/tag/v3.0.0-0

**Comment by kwonoj** [comment]
Yes, seems it's working as expected. Appreciate for quick update! 🙇

**Comment by kwonoj** [comment]
@terehov just found one regression in 3.0.0, created PR https://github.com/fullstack-build/tslog/pull/68.
