### ISSUE TITLE
Bug: Method names for async functions not showing

### ISSUE THREAD

**Issue by businessrate** [fullstack-build/tslog#64]
Opened accidently from a client account.  Please delete.  Created new issue

**Comment by businessrate** [comment]
I know it is stupid - but would you mind fully deleting this issue in order to get it off this account?  It causes the project to show in my clients account.  Sorry for making more work for you.

**Comment by terehov** [comment]
That's alright, no worries. I'm afraid it's not possible to delete an issue on a public project. I can only delete a comment, the revision history, but not the issue itself. If you can figure out how to do it, I would be happy to help. I believe the best way is to directly contact GitHub support as the author of the issue. I guess they will be able to help you.

**Comment by businessrate** [comment]
Thanks for all the help.  You are awesome.  I found this: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/deleting-an-issue

But that might not apply to a public project.
