### ISSUE TITLE
Bug: maskValuesOfKeys option mutates object properties!

### ISSUE THREAD

**Issue by deman4ik** [fullstack-build/tslog#66]
**To Reproduce**
```ts
import { Logger } from "tslog";

const logger = new Logger();

const password = "123";
const someObj = {
    password: "123"
};

logger.info(someObj);
logger.info(password);

console.log(password === "123"); // true
console.log(someObj.password === "123"); // false

```

**Additional context**
v2.11.1

**Node.js Version**
v14.15.1

**Comment by terehov** [comment]
That's actually done by design.
https://github.com/fullstack-build/tslog#maskvaluesofkeys

You can change this default behaviore with an `maskValuesOfKeys ` empty array: 

```javascript
const logger = new Logger({ maskValuesOfKeys: [] });

const password = "123";
const someObj = {
    password: "123"
};

logger.info(someObj);
logger.info(password);

console.log(password === "123"); // true
console.log(someObj.password === "123"); // true
```

**Comment by deman4ik** [comment]
@terehov Why not just clone object, mask and log it but not mutate the original one?

**Comment by terehov** [comment]
Oh, I think I got your problem. I’m in the middle of a bigger release anyway, going to fix it as well.

**Comment by terehov** [comment]
I have just released a new version as `next` including these changes: 

https://github.com/fullstack-build/tslog/releases/tag/v3.0.0-0

**Comment by terehov** [comment]
@deman4ik 
Can you please let me know if it wors as expected? Thank you.

**Comment by deman4ik** [comment]
> @deman4ik
> Can you please let me know if it wors as expected? Thank you.

Yes it works! Thank you.
