### ISSUE TITLE
Feature Request: Allow custom delimiters

### ISSUE THREAD

**Issue by aliak00** [fullstack-build/tslog#67]
**Description / Use Case for a Feature**
The use case is for formatting the logs with more customization.

Right now my logs look like:
![image](https://user-images.githubusercontent.com/2638284/99699877-c98d3b00-2a92-11eb-90c8-c4914013768e.png)

I would like to be able to not have all the spaces between the meta information but still have the colored output with log levels and time. Is that possible or would it be a feature request?

**Comment by Taruga** [comment]
I also would like to have the right part of the logs aligned
![Screenshot 2020-11-23 at 02 17 15](https://user-images.githubusercontent.com/1231549/99924384-032fa180-2d32-11eb-9095-0dcf884e4b78.png)

**Comment by terehov** [comment]
Just to get it correct: So you basically would prefer spaces instead of tabs as the delimiter. I guess that's the reason why it doesn't look that alligned. I am gonna add it with the upcoming release and probably also change the default behavior.

**Comment by terehov** [comment]
I have just released a new version as `next` including these changes: 

https://github.com/fullstack-build/tslog/releases/tag/v3.0.0-0
