### ISSUE TITLE
Is there a way to silent logging when running unit tests using jest

### ISSUE THREAD

**Issue by MRaahulVignesh** [fullstack-build/tslog#69]
I am using tslog and jest for writing unit tests. I wanted to check if there is a way to silent the tslog when running unit tests without using any jest configuration?

**Comment by terehov** [comment]
Sorry, I don't quite get your request? 
You can always set https://github.com/fullstack-build/tslog#type `type` to `hidden`.

**Comment by MRaahulVignesh** [comment]
Hey,
Sorry for not providing you with better details. Let me explain to you more. Right now, I am using Tslog for performing logs in my backend service. When running jest unit test cases for my service, my Tslogs are also printing which unnecessarily clogs my terminal. Therefore, I am currently using jest mock functions for mocking Tslog and preventing them from printing logs. Now, I am asking if there is a better way to achieve this behavior directly using Tslog. 

I got your idea of setting type to hidden. let me see if I can achieve the same behavior using this.

Thank you!

**Comment by terehov** [comment]
Ok, understood. But I believe it is a generic, more a JavaScript than `tslog` related question. 
Essentially there are many ways to achieve this. You could, for example, set the `type` based on the `environment`. Let's say you have a `production` and a `testing` one. When in testing, `type` would be set to `hidden`.

`tslog` is just a logger, that provides you with an API to develop against. However, you still would have to adopt it to your use case.
