### ISSUE TITLE
Error when trying to access relevant call sites

### ISSUE THREAD

**Issue by passionkind** [fullstack-build/tslog#71]
I am currently trying to integrate tslog in a nextjs api function. I stumbled upon an error where `relevantCallSites` turned out to be an array of 3 elements. Since the default for `ignoreStackLevels` seems to be `3`, it makes sense that `undefined` cannot be evaluated. 

I haven't yet tracked down why my callsites only have a length of 3 but in any case, it'd be better to check if `relevantCallSites.length > 0` and not pass it down in case there is no `CallSite` left. 

https://github.com/fullstack-build/tslog/blob/2e0d103ba4ba9ee1aefe2bc0f0330e67271ea44b/src/LoggerWithoutCallSite.ts#L372-L374

**Comment by terehov** [comment]
Thanks for reporting and sorry that it took me so long this time. 
I fixed it in 3.0.2:
https://github.com/fullstack-build/tslog/releases/tag/v3.0.2
