### ISSUE TITLE
Bug: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by flybayer** [fullstack-build/tslog#78]
**Describe the bug**

These both fail as of `3.0.3`. They worked fine in `2.9.1`

**To Reproduce**

```ts
logger.info("A", null)
logger.info("B", undefined)
```

**Expected behavior**
Logger should accept all values, especially null and undefined.

**Node.js Version**
12

**OS incl. Version**
  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.43 GB / 64.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish

**Comment by terehov** [comment]
Thank you very much. A bugfix is coming soon.

**Comment by terehov** [comment]
Fixed: 

https://github.com/fullstack-build/tslog/releases/tag/v3.0.5

**Comment by flybayer** [comment]
Thank you!
