### ISSUE TITLE
Bug: Logs are blank in Sentry breadcrumbs

### ISSUE THREAD

**Issue by flybayer** [fullstack-build/tslog#81]
**Describe the bug**

Here's what tslog looks like in Sentry breadcrumbs with `pretty` logging:

![image](https://user-images.githubusercontent.com/8813276/104109939-c51a1d00-52a0-11eb-96a7-41d8bc7b8177.png)

This is captured to sentry in Node like this:

```ts
  } catch (error) {
    Sentry.captureException(error)
    throw error
  }
```

Not sure what the core issue is 🤷 

**Expected behavior**
Pretty logs would show up correctly

**Comment by flybayer** [comment]
Update: I'm now using JSON logs but they are still blank in Sentry...

**Comment by terehov** [comment]
Interesting. Would you share how you integrated Sentry? 

This is how I did it (through `transports`)
```typescript
    // Sentry
    if (this.logConfig.isSentryEnabled) {
      Sentry.init({
        dsn: this.logConfig.sentryDsn,
        maxBreadcrumbs: this.logConfig.sentryMaxBreadcrumbs,
        debug: this.logConfig.sentryDebug,
        serverName: hostname(),
        tracesSampleRate: this.logConfig.sentryTracesSampleRate,
        environment: process.env.NODE_ENV,
        release: `${process.env.npm_package_name}@${process.env.npm_package_version}`,
        integrations: [
          // enable HTTP calls tracing
          new Sentry.Integrations.Http({ tracing: true })
        ]
      });

      loggerFactory.logger.attachTransport(
        {
          silly: this.logToSentry,
          debug: this.logToSentry,
          trace: this.logToSentry,
          info: this.logToSentry,
          warn: this.logToSentry,
          error: this.logToSentry,
          fatal: this.logToSentry
        },
        this.logConfig.sentryMinLevel
      );
    }
```

and
```typescript


  private logToSentry = async (logObject: tslog.ILogObject) => {
    // send only exceptions to Sentry
    logObject?.argumentsArray?.forEach((argument: tslog.IErrorObject) => {
      if (argument.isError === true) {
        Sentry.captureException(argument.nativeError);
      }
    });
  };
```

**Comment by flybayer** [comment]
@terehov I did not use any special integration, am just relying on Sentry's automatic pickup of console.log.

That is definitely interesting, but would be nice if it could just work without that.

**Comment by amolpatel** [comment]
@flybayer Were you able to find a workaround for this? I like and could use @terehov's solution but it is a bit hacky.

**Comment by terehov** [comment]
In V4 I am going to use `console`per default, rather than Stdout. I believe that should be more compatible with Sentry per default.

**Comment by terehov** [comment]
As mentioned before, V4 uses console per default (can be overwritten though) and is even more flexible and allows overwriting every part of the log processing. 
Give it a go and let me know if that solves your problem: 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

Thank you.

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)

**Comment by kristianeboe** [comment]
Logs still show up like this for me in Sentry
<img width="419" alt="image" src="https://github.com/user-attachments/assets/c2481c04-b9c6-430e-bcb5-0108e770851d">
