### ISSUE TITLE
Bug: logging an Error object with colorizePrettyLogs: false throws a ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by markayers** [fullstack-build/tslog#82]
**Describe the bug**
logging an Error object with colorizePrettyLogs: false throws a ERR_INVALID_ARG_TYPE

**To Reproduce**
https://github.com/markayers/tslog-error-bug-repro

**Expected behavior**
a stacktrace log without ansi color codes

**PR**
#83

**Node.js Version**
12.19.0

**OS incl. Version**
Windows 10 Pro v2004 build 19041.746

**Comment by terehov** [comment]
Thank you very much for your repo and your MR. I'll release it soon.

**Comment by markayers** [comment]
Happy to help! Love the library, we're in a pre-beta testing phase and don't have log aggregation set up yet, so we're using pretty logs instead of JSON in our deployed environments for now. Azure App Service log stream doesn't support ANSI color codes so we were running into this on every error log.
