### ISSUE TITLE
Bug: `Cannot read property 'isError' of null`

### ISSUE THREAD

**Issue by flybayer** [fullstack-build/tslog#85]
**Describe the bug**

tslog version: `3.1.0`

Unfortunately I don't know how to reproduce this but I periodically get an error thrown by tslog of `Cannot read property 'isError' of null` while attempting to log a message with a JS object. I see this usually in production. Although I think I've also seen it in local dev.

**Expected behavior**

Should not error

**Additional context**

```ts
import { Logger } from "tslog"

export const logger = new Logger({
  type: clientEnv.isProduction ? "json" : "pretty",
  dateTimePattern: "hour:minute:second.millisecond",
  displayFunctionName: false,
  displayFilePath: "hidden",
  dateTimeTimezone: clientEnv.isProduction
    ? "utc"
    : Intl.DateTimeFormat().resolvedOptions().timeZone,
  prettyInspectHighlightStyles: { name: "yellow", number: "blue", bigint: "blue", boolean: "blue" },
  maskValuesOfKeys: ["password", "passwordConfirmation"],
  exposeErrorCodeFrame: !clientEnv.isProduction,
})


// And then I'm also using a child logger
const log = logger.getChildLogger({ prefix: ["submitGroupStep1()"] })

```

**Node.js Version**
12

**Comment by terehov** [comment]
I tried multiple things and wasn't really able to reproduce this issue and also couldn't find that error in my logs. 
However, I've found one spot with a missing optional chaining, which I added. So I really hope 🤞 that it solves this issue.

**Comment by terehov** [comment]
Would be awesome, if you could let me know if this problem still present with this version. Thank you. 

https://github.com/fullstack-build/tslog/releases/tag/v3.1.1
