### ISSUE TITLE
How to disable short path in log message?

### ISSUE THREAD

**Issue by vladgolubev** [fullstack-build/tslog#9]
Thanks for such an awesome library! I've been using it in next.js project, but unfortunately, I was not able to get helpful "short paths" due to the way how next.js works

Can I disable them? I looked at the available settings, but haven't found one.

Thanks!

![image](https://user-images.githubusercontent.com/3817380/83802284-20ed4980-a6b3-11ea-81b6-f562c5e05017.png)

**Comment by terehov** [comment]
Hey Vlad, 

thanks for your kind words! 
Good idea, I am going to add a setting for that 👍

**Comment by terehov** [comment]
Thanks for hanging in!

I just released a new version `2.2.0` with many new additional settings for display control, e.g. new lines, date format, time zone, and also the one you were asking for `displayFilePath`:

https://tslog.js.org/#/?id=displayfilepath 

Check it out and let me know if it suits your use case :-)

**Comment by vladgolubev** [comment]
@terehov thanks for such a quick turnaround!

I've just tried and it works!

![image](https://user-images.githubusercontent.com/3817380/83914877-c61f2500-a77a-11ea-8308-00c34a867b13.png)
