### ISSUE TITLE
Bug: Absolute paths using ES modules in Node

### ISSUE THREAD

**Issue by vanntile** [fullstack-build/tslog#99]
**Describe the bug**
In the module description, it says

> Paths are relative to the root of the application folder

Using node ES modules in an express project, the paths are not relative, but absolute from the system root.

**To Reproduce**
The logger module file is below

```js
import { Logger } from 'tslog'

const logger = new Logger({
  name: 'log',
  displayLoggerName: false,
  printLogMessageInNewLine: true,
  overwriteConsole: true,
})

export default logger
```

Using it like the following:

```js
import logger from './utils/logger.mjs'

logger.info(`Connecting to ${config.PORT}`)

const err = new Error('Test Error')
logger.prettyError(err)
```

The output is

```
2021-04-18 06:56:20.482  INFO [file:///home/vanntile/src/tests/nn/src/app.mjs:12 undefined.<anonymous>]
Connecting to 8080 

 Error  Test Error
error stack:
• app.mjs:24 <anonymous>
    file:/home/vanntile/src/tests/nn/src/app.mjs:24:13
```

**Expected behavior**
The paths being relative from the project root.

**Additional context**
This happens both when running with node and `nodemon`.

**Node.js Version**
14.15.3

**npm Version**
7.9.0

**OS incl. Version**
Ubuntu 20.04

**Comment by ScorpionConMate** [comment]
Did you get any solution?

**Comment by vanntile** [comment]
> Did you get any solution?

No, I haven't tried anymore and moved to pino

**Comment by beanaroo** [comment]
I found that `stackFrame.getFileName()` at [LoggerHelper.ts#L75](https://github.com/fullstack-build/tslog/blob/0d2ccadb262879153271e26d98b7e80334337c64/src/LoggerHelper.ts#L75) returns a path prefixed with `file://` when using ES Modules.

Stripping it in [cleanUpFilePath](https://github.com/fullstack-build/tslog/blob/0d2ccadb262879153271e26d98b7e80334337c64/src/LoggerHelper.ts#L22) seems to restore functionality as documented.

If this is a possible solution, I'm happy to open a PR

**Comment by beanaroo** [comment]
I just noticed that Code Frame is also not printed when using ES Modules.

Modifying [LoggerHelper.ts#L75](https://github.com/fullstack-build/tslog/blob/0d2ccadb262879153271e26d98b7e80334337c64/src/LoggerHelper.ts#L75) instead restores both relative paths and code frames:

```typescript
    const filePath: string | null = stackFrame.getFileName().replace("file://", "");
```

**Comment by terehov** [comment]
Yes, a PR would be great! Thanks for this hint! 👍🏻
